version: '3.8'

services:
  # RemoteClaude Server - macOS Host
  remoteclaude-server:
    build: 
      context: ../server
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    environment:
      - REMOTECLAUDE_PORT=8090
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ../projects:/app/projects
      - ./configs:/app/configs
    networks:
      - remoteclaude-network
    restart: unless-stopped

  # Secure Project Container Template
  project-template:
    build: 
      context: ./ubuntu-claude
      dockerfile: Dockerfile
    profiles:
      - template
    environment:
      - PROJECT_ID=template
      - CLAUDE_API_KEY=${CLAUDE_API_KEY}
    volumes:
      - project-workspace:/workspace
    working_dir: /workspace
    networks:
      - remoteclaude-network
    security_opt:
      - no-new-privileges:true
    user: "1000:1000"
    mem_limit: 2g
    cpus: 1.0
    
  # VPN Gateway (WireGuard)
  wireguard:
    image: lscr.io/linuxserver/wireguard:latest
    container_name: remoteclaude-vpn
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Tokyo
      - SERVERURL=auto
      - SERVERPORT=51820
      - PEERS=iphone,laptop,tablet
      - PEERDNS=auto
      - INTERNAL_SUBNET=10.13.13.0
      - ALLOWEDIPS=0.0.0.0/0
    volumes:
      - ./wireguard-config:/config
      - /lib/modules:/lib/modules
    ports:
      - "51820:51820/udp"
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
    networks:
      - remoteclaude-network

  # Nginx Reverse Proxy with SSL
  nginx:
    image: nginx:alpine
    container_name: remoteclaude-proxy
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - remoteclaude-server
    networks:
      - remoteclaude-network
    restart: unless-stopped

networks:
  remoteclaude-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  project-workspace:
    driver: local