import React, { useState } from 'react';
import {
  View,
  Text,
  TouchableOpacity,
  StyleSheet,
  Alert,
  ActivityIndicator,
  Modal,
  ScrollView,
  Animated,
  Vibration,
} from 'react-native';
import { LinearGradient } from 'expo-linear-gradient';
import { Ionicons } from '@expo/vector-icons';

interface AutoGeneratedButtonConfig {
  id: string;
  title: string;
  description: string;
  category: string;
  command: string;
  execution_type: string;
  expected_output: string;
  button_config: {
    type: string;
    icon: string;
    color: string;
    gradient: string[];
    priority: number;
  };
  wandb_metadata?: {
    experiment_id: string;
    run_id: string;
    project_name: string;
    run_name: string;
    tags: string[];
    metrics: {
      confidence_score: number;
      priority: number;
      execution_count?: number;
      execution_success?: number;
    };
  };
  created_at: string;
  source: string;
}

interface AutoGeneratedButtonProps {
  config: AutoGeneratedButtonConfig;
  onExecute: (button: AutoGeneratedButtonConfig) => Promise<{
    success: boolean;
    output?: string;
    error?: string;
    matplotlib_data?: any;
  }>;
  projectId: string;
}

const AutoGeneratedButton: React.FC<AutoGeneratedButtonProps> = ({
  config,
  onExecute,
  projectId,
}) => {
  const [isExecuting, setIsExecuting] = useState(false);
  const [showDetails, setShowDetails] = useState(false);
  const [lastOutput, setLastOutput] = useState<string | null>(null);
  const [lastError, setLastError] = useState<string | null>(null);
  const [executionCount, setExecutionCount] = useState(
    config.wandb_metadata?.metrics.execution_count || 0
  );
  const animatedValue = new Animated.Value(0);

  React.useEffect(() => {
    Animated.loop(
      Animated.sequence([
        Animated.timing(animatedValue, {
          toValue: 1,
          duration: 3000,
          useNativeDriver: true,
        }),
        Animated.timing(animatedValue, {
          toValue: 0,
          duration: 3000,
          useNativeDriver: true,
        }),
      ])
    ).start();
  }, []);

  const categoryIcons = {
    web_app: 'globe-outline' as const,
    data_visualization: 'analytics-outline' as const,
    machine_learning: 'brain-outline' as const,
    database_operations: 'server-outline' as const,
    api_development: 'link-outline' as const,
    docker_container: 'cube-outline' as const,
    file_operations: 'document-outline' as const,
    testing_automation: 'flask-outline' as const,
  };

  const categoryColors = {
    web_app: ['#00d4aa', '#00b4d8'],
    data_visualization: ['#ff6b35', '#f7931e'],
    machine_learning: ['#8e44ad', '#9b59b6'],
    database_operations: ['#27ae60', '#2ecc71'],
    api_development: ['#3498db', '#2980b9'],
    docker_container: ['#0db7ed', '#2496ed'],
    file_operations: ['#f39c12', '#e67e22'],
    testing_automation: ['#e74c3c', '#c0392b'],
  };

  const getButtonConfig = () => {
    const category = config.category as keyof typeof categoryColors;
    return {
      icon: categoryIcons[category] || config.button_config.icon,
      gradient: categoryColors[category] || config.button_config.gradient,
      color: config.button_config.color,
    };
  };

  const buttonConfig = getButtonConfig();

  const handleExecute = async () => {
    setIsExecuting(true);
    Vibration.vibrate(100);

    try {
      const result = await onExecute(config);

      if (result.success) {
        setLastOutput(result.output || 'Auto-generated command executed successfully');
        setLastError(null);
        setExecutionCount(prev => prev + 1);

        Alert.alert(
          '🤖 Auto-Generated Command Success',
          `${config.title}\\n\\nOutput: ${result.output || 'Executed successfully'}`,
          [{ text: 'OK', style: 'default' }]
        );

        // Handle matplotlib data if available
        if (result.matplotlib_data) {
          Alert.alert(
            '📊 Visualization Generated',
            'Plot has been generated and is available in Preview!',
            [{ text: 'View Preview', style: 'default' }]
          );
        }
      } else {
        setLastError(result.error || 'Auto-generated command failed');
        setLastOutput(null);
        Alert.alert(
          '❌ Auto-Generated Command Failed',
          `Error: ${result.error || 'Unknown error occurred'}`,
          [{ text: 'OK', style: 'cancel' }]
        );
      }
    } catch (error: any) {
      setLastError(error.message || 'Execution failed');
      setLastOutput(null);
      Alert.alert(
        '❌ Execution Error',
        `Failed to execute auto-generated command: ${error.message || 'Unknown error'}`,
        [{ text: 'OK', style: 'cancel' }]
      );
    } finally {
      setIsExecuting(false);
    }
  };

  const getConfidenceColor = (score: number) => {
    if (score >= 0.8) return '#4CAF50';
    if (score >= 0.6) return '#FF9800';
    return '#F44336';
  };

  const renderDetailModal = () => (
    <Modal
      visible={showDetails}
      animationType="slide"
      presentationStyle="pageSheet"
      onRequestClose={() => setShowDetails(false)}
    >
      <View style={styles.modalContainer}>
        <View style={[styles.modalHeader, { backgroundColor: buttonConfig.color }]}>
          <View style={styles.modalHeaderContent}>
            <Text style={styles.modalTitle}>{config.title}</Text>
            <View style={styles.autoGeneratedBadge}>
              <Ionicons name="sparkles" size={12} color="#fff" />
              <Text style={styles.autoGeneratedText}>Auto-Generated</Text>
            </View>
          </View>
          <TouchableOpacity
            style={styles.closeButton}
            onPress={() => setShowDetails(false)}
          >
            <Ionicons name="close" size={24} color="#fff" />
          </TouchableOpacity>
        </View>

        <ScrollView style={styles.modalContent}>
          <View style={styles.detailSection}>
            <Text style={styles.sectionTitle}>🤖 AI生成コマンド詳細</Text>
            <Text style={styles.detailText}>{config.description}</Text>
          </View>

          <View style={styles.detailSection}>
            <Text style={styles.sectionTitle}>💻 実行コマンド</Text>
            <View style={styles.commandBox}>
              <Text style={styles.commandText}>{config.command}</Text>
            </View>
          </View>

          <View style={styles.detailSection}>
            <Text style={styles.sectionTitle}>📊 W&B統合メタデータ</Text>
            {config.wandb_metadata ? (
              <View style={styles.metadataGrid}>
                <View style={styles.metadataItem}>
                  <Text style={styles.metadataLabel}>信頼度スコア</Text>
                  <View style={[
                    styles.confidenceBadge,
                    { backgroundColor: getConfidenceColor(config.wandb_metadata.metrics.confidence_score) }
                  ]}>
                    <Text style={styles.confidenceText}>
                      {(config.wandb_metadata.metrics.confidence_score * 100).toFixed(1)}%
                    </Text>
                  </View>
                </View>
                <View style={styles.metadataItem}>
                  <Text style={styles.metadataLabel}>実行回数</Text>
                  <Text style={styles.metadataValue}>{executionCount}回</Text>
                </View>
                <View style={styles.metadataItem}>
                  <Text style={styles.metadataLabel}>カテゴリ</Text>
                  <Text style={styles.metadataValue}>{config.category}</Text>
                </View>
                <View style={styles.metadataItem}>
                  <Text style={styles.metadataLabel}>プロジェクト</Text>
                  <Text style={styles.metadataValue}>{config.wandb_metadata.project_name}</Text>
                </View>
              </View>
            ) : (
              <Text style={styles.detailText}>メタデータなし</Text>
            )}
          </View>

          <View style={styles.detailSection}>
            <Text style={styles.sectionTitle}>🎯 期待される出力</Text>
            <Text style={styles.detailText}>{config.expected_output}</Text>
          </View>

          {config.wandb_metadata?.tags && (
            <View style={styles.detailSection}>
              <Text style={styles.sectionTitle}>🏷️ タグ</Text>
              <View style={styles.tagContainer}>
                {config.wandb_metadata.tags.map((tag, index) => (
                  <View key={index} style={styles.tag}>
                    <Text style={styles.tagText}>{tag}</Text>
                  </View>
                ))}
              </View>
            </View>
          )}

          {lastOutput && (
            <View style={styles.detailSection}>
              <Text style={styles.sectionTitle}>✅ 最新の出力</Text>
              <View style={styles.outputBox}>
                <Text style={styles.outputText}>{lastOutput}</Text>
              </View>
            </View>
          )}

          {lastError && (
            <View style={styles.detailSection}>
              <Text style={styles.sectionTitle}>❌ 最新のエラー</Text>
              <View style={styles.errorBox}>
                <Text style={styles.errorText}>{lastError}</Text>
              </View>
            </View>
          )}
        </ScrollView>

        <View style={styles.modalFooter}>
          <TouchableOpacity
            style={styles.executeButton}
            onPress={() => {
              setShowDetails(false);
              handleExecute();
            }}
            disabled={isExecuting}
          >
            <LinearGradient
              colors={buttonConfig.gradient}
              style={styles.executeButtonGradient}
            >
              {isExecuting ? (
                <>
                  <ActivityIndicator color="#fff" size="small" />
                  <Text style={styles.executeButtonText}>実行中...</Text>
                </>
              ) : (
                <>
                  <Ionicons name="flash-outline" size={20} color="#fff" />
                  <Text style={styles.executeButtonText}>自動実行</Text>
                </>
              )}
            </LinearGradient>
          </TouchableOpacity>
        </View>
      </View>
    </Modal>
  );

  const animatedOpacity = animatedValue.interpolate({
    inputRange: [0, 1],
    outputRange: [0.8, 1],
  });

  const animatedScale = animatedValue.interpolate({
    inputRange: [0, 1],
    outputRange: [1, 1.02],
  });

  return (
    <View style={styles.container}>
      <Animated.View style={[
        styles.animatedContainer,
        {
          opacity: animatedOpacity,
          transform: [{ scale: animatedScale }]
        }
      ]}>
        <TouchableOpacity
          style={styles.commandButton}
          onPress={() => setShowDetails(true)}
          onLongPress={handleExecute}
          activeOpacity={0.8}
        >
          <LinearGradient
            colors={buttonConfig.gradient}
            style={styles.buttonGradient}
          >
            <View style={styles.buttonContent}>
              <View style={styles.buttonIcon}>
                <Ionicons name={buttonConfig.icon} size={24} color="#fff" />
                <View style={styles.autoIndicator}>
                  <Ionicons name="sparkles" size={10} color="#fff" />
                </View>
                {isExecuting && (
                  <View style={styles.executingIndicator}>
                    <ActivityIndicator size="small" color="#fff" />
                  </View>
                )}
              </View>

              <View style={styles.buttonTextContainer}>
                <Text style={styles.buttonTitle}>{config.title}</Text>
                <Text style={styles.buttonDescription} numberOfLines={2}>
                  {config.description}
                </Text>
                <View style={styles.buttonMeta}>
                  <Text style={styles.buttonMetaText}>
                    🤖 AI生成 | {config.category}
                  </Text>
                  {config.wandb_metadata && (
                    <Text style={styles.confidenceText}>
                      信頼度: {(config.wandb_metadata.metrics.confidence_score * 100).toFixed(0)}%
                    </Text>
                  )}
                </View>
              </View>

              <View style={styles.buttonActions}>
                <View style={styles.executionCount}>
                  <Text style={styles.executionCountText}>{executionCount}</Text>
                </View>
                <Ionicons name="chevron-forward" size={16} color="#fff" />
              </View>
            </View>
          </LinearGradient>
        </TouchableOpacity>
      </Animated.View>

      {renderDetailModal()}
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    marginVertical: 4,
  },
  animatedContainer: {
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },
  commandButton: {
    borderRadius: 12,
    overflow: 'hidden',
  },
  buttonGradient: {
    padding: 12,
  },
  buttonContent: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  buttonIcon: {
    position: 'relative',
    marginRight: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  autoIndicator: {
    position: 'absolute',
    top: -6,
    right: -6,
    backgroundColor: 'rgba(255,255,255,0.3)',
    borderRadius: 8,
    padding: 2,
  },
  executingIndicator: {
    position: 'absolute',
    top: -8,
    right: -8,
  },
  buttonTextContainer: {
    flex: 1,
  },
  buttonTitle: {
    color: '#fff',
    fontSize: 13,
    fontWeight: 'bold',
    marginBottom: 2,
  },
  buttonDescription: {
    color: '#fff',
    fontSize: 10,
    opacity: 0.9,
    lineHeight: 12,
    marginBottom: 2,
  },
  buttonMeta: {
    flexDirection: 'column',
  },
  buttonMetaText: {
    color: '#fff',
    fontSize: 8,
    opacity: 0.8,
  },
  confidenceText: {
    color: '#fff',
    fontSize: 8,
    opacity: 0.9,
    fontWeight: '600',
  },
  buttonActions: {
    alignItems: 'center',
    marginLeft: 6,
  },
  executionCount: {
    backgroundColor: 'rgba(255,255,255,0.2)',
    borderRadius: 10,
    paddingHorizontal: 6,
    paddingVertical: 2,
    marginBottom: 2,
  },
  executionCountText: {
    color: '#fff',
    fontSize: 8,
    fontWeight: 'bold',
  },
  modalContainer: {
    flex: 1,
    backgroundColor: '#1a1a1a',
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#444',
  },
  modalHeaderContent: {
    flex: 1,
  },
  modalTitle: {
    color: '#fff',
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 4,
  },
  autoGeneratedBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.2)',
    borderRadius: 12,
    paddingHorizontal: 8,
    paddingVertical: 2,
    alignSelf: 'flex-start',
  },
  autoGeneratedText: {
    color: '#fff',
    fontSize: 10,
    marginLeft: 4,
  },
  closeButton: {
    padding: 8,
  },
  modalContent: {
    flex: 1,
    padding: 20,
  },
  detailSection: {
    marginBottom: 20,
  },
  sectionTitle: {
    color: '#fff',
    fontSize: 14,
    fontWeight: 'bold',
    marginBottom: 8,
  },
  detailText: {
    color: '#ccc',
    fontSize: 13,
    lineHeight: 18,
  },
  commandBox: {
    backgroundColor: '#2a2a2a',
    padding: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#444',
  },
  commandText: {
    color: '#00ff00',
    fontSize: 12,
    fontFamily: 'monospace',
  },
  metadataGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  metadataItem: {
    flex: 1,
    minWidth: 120,
  },
  metadataLabel: {
    color: '#888',
    fontSize: 11,
    marginBottom: 4,
  },
  metadataValue: {
    color: '#fff',
    fontSize: 12,
    fontWeight: '600',
  },
  confidenceBadge: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
    alignSelf: 'flex-start',
  },
  tagContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
  },
  tag: {
    backgroundColor: '#333',
    borderRadius: 12,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  tagText: {
    color: '#fff',
    fontSize: 10,
  },
  outputBox: {
    backgroundColor: '#0d4427',
    padding: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#4CAF50',
  },
  outputText: {
    color: '#4CAF50',
    fontSize: 12,
    fontFamily: 'monospace',
  },
  errorBox: {
    backgroundColor: '#4a1a1a',
    padding: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#F44336',
  },
  errorText: {
    color: '#F44336',
    fontSize: 12,
    fontFamily: 'monospace',
  },
  modalFooter: {
    padding: 20,
    backgroundColor: '#2a2a2a',
    borderTopWidth: 1,
    borderTopColor: '#444',
  },
  executeButton: {
    borderRadius: 12,
    overflow: 'hidden',
  },
  executeButtonGradient: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 14,
    gap: 8,
  },
  executeButtonText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: 'bold',
  },
});

export default AutoGeneratedButton;