// DuplicateButtonFilter.ts - 重複ボタンの除去とフィルタリング
export interface ButtonConfig {
  id: string;
  name: string;
  description: string;
  command: string;
  type: string;
  category: string;
}

export interface AutoGeneratedButtonConfig {
  id: string;
  title: string;
  description: string;
  category: string;
  command: string;
  execution_type: string;
  button_config: {
    type: string;
    icon: string;
    color: string;
    gradient: string[];
    priority: number;
  };
  wandb_metadata?: any;
  created_at: string;
  source: string;
}

export class DuplicateButtonFilter {

  // コマンドの類似性を判定する
  private static calculateCommandSimilarity(cmd1: string, cmd2: string): number {
    // 基本的な前処理
    const normalize = (cmd: string) =>
      cmd.toLowerCase()
         .replace(/['"]/g, '')
         .replace(/\s+/g, ' ')
         .trim();

    const norm1 = normalize(cmd1);
    const norm2 = normalize(cmd2);

    // 完全一致
    if (norm1 === norm2) return 1.0;

    // 包含関係チェック
    if (norm1.includes(norm2) || norm2.includes(norm1)) return 0.8;

    // 基本コマンド抽出（最初の単語）
    const baseCmd1 = norm1.split(' ')[0];
    const baseCmd2 = norm2.split(' ')[0];

    if (baseCmd1 === baseCmd2) return 0.6;

    // Levenshtein距離による類似度
    const distance = this.levenshteinDistance(norm1, norm2);
    const maxLength = Math.max(norm1.length, norm2.length);
    return 1 - (distance / maxLength);
  }

  // レーベンシュタイン距離計算
  private static levenshteinDistance(str1: string, str2: string): number {
    const matrix = Array(str2.length + 1).fill(null).map(() => Array(str1.length + 1).fill(null));

    for (let i = 0; i <= str1.length; i += 1) {
      matrix[0][i] = i;
    }

    for (let j = 0; j <= str2.length; j += 1) {
      matrix[j][0] = j;
    }

    for (let j = 1; j <= str2.length; j += 1) {
      for (let i = 1; i <= str1.length; i += 1) {
        const indicator = str1[i - 1] === str2[j - 1] ? 0 : 1;
        matrix[j][i] = Math.min(
          matrix[j][i - 1] + 1, // deletion
          matrix[j - 1][i] + 1, // insertion
          matrix[j - 1][i - 1] + indicator // substitution
        );
      }
    }

    return matrix[str2.length][str1.length];
  }

  // 重複除去閾値
  private static SIMILARITY_THRESHOLD = 0.7;

  // 通常のボタンから重複を除去
  static removeDuplicateButtons(buttons: ButtonConfig[]): ButtonConfig[] {
    const unique: ButtonConfig[] = [];

    for (const button of buttons) {
      const isDuplicate = unique.some(existing => {
        const similarity = this.calculateCommandSimilarity(button.command, existing.command);
        return similarity > this.SIMILARITY_THRESHOLD;
      });

      if (!isDuplicate) {
        unique.push(button);
      }
    }

    return unique;
  }

  // 自動生成ボタンから重複を除去
  static removeDuplicateAutoButtons(buttons: AutoGeneratedButtonConfig[]): AutoGeneratedButtonConfig[] {
    const unique: AutoGeneratedButtonConfig[] = [];

    for (const button of buttons) {
      const isDuplicate = unique.some(existing => {
        // コマンドの類似性チェック
        const cmdSimilarity = this.calculateCommandSimilarity(button.command, existing.command);

        // タイトルの類似性チェック
        const titleSimilarity = this.calculateCommandSimilarity(button.title, existing.title);

        // カテゴリが同じで、コマンドまたはタイトルが類似している場合は重複とみなす
        return (button.category === existing.category) &&
               (cmdSimilarity > this.SIMILARITY_THRESHOLD || titleSimilarity > this.SIMILARITY_THRESHOLD);
      });

      if (!isDuplicate) {
        unique.push(button);
      }
    }

    return unique;
  }

  // 通常ボタンと自動生成ボタンの重複を除去
  static removeCrossButtonDuplicates(
    normalButtons: ButtonConfig[],
    autoButtons: AutoGeneratedButtonConfig[]
  ): {
    uniqueNormal: ButtonConfig[];
    uniqueAuto: AutoGeneratedButtonConfig[];
  } {
    const uniqueNormal: ButtonConfig[] = [];
    const uniqueAuto: AutoGeneratedButtonConfig[] = [];

    // 通常ボタンの重複除去
    for (const normalBtn of normalButtons) {
      const hasDuplicateInAuto = autoButtons.some(autoBtn => {
        const similarity = this.calculateCommandSimilarity(normalBtn.command, autoBtn.command);
        return similarity > this.SIMILARITY_THRESHOLD;
      });

      if (!hasDuplicateInAuto) {
        uniqueNormal.push(normalBtn);
      }
    }

    // 自動生成ボタンの重複除去（より高い信頼度を持つものを優先）
    for (const autoBtn of autoButtons) {
      const hasDuplicateInNormal = normalButtons.some(normalBtn => {
        const similarity = this.calculateCommandSimilarity(autoBtn.command, normalBtn.command);
        return similarity > this.SIMILARITY_THRESHOLD;
      });

      // 信頼度が高い自動生成ボタンは通常ボタンより優先
      const confidence = autoBtn.wandb_metadata?.metrics?.confidence_score || 0;
      if (!hasDuplicateInNormal || confidence > 0.8) {
        uniqueAuto.push(autoBtn);
      }
    }

    return { uniqueNormal, uniqueAuto };
  }

  // ボタンを優先度とカテゴリでソート
  static sortButtonsByPriority(buttons: AutoGeneratedButtonConfig[]): AutoGeneratedButtonConfig[] {
    return buttons.sort((a, b) => {
      // 信頼度スコアで比較
      const confidenceA = a.wandb_metadata?.metrics?.confidence_score || 0;
      const confidenceB = b.wandb_metadata?.metrics?.confidence_score || 0;

      if (confidenceA !== confidenceB) {
        return confidenceB - confidenceA; // 高い信頼度を優先
      }

      // Priorityで比較（低い数値が高い優先度）
      const priorityA = a.button_config?.priority || 999;
      const priorityB = b.button_config?.priority || 999;

      if (priorityA !== priorityB) {
        return priorityA - priorityB;
      }

      // カテゴリ別優先度
      const categoryPriority: { [key: string]: number } = {
        'web_app': 1,
        'data_visualization': 2,
        'machine_learning': 3,
        'database_operations': 4,
        'api_development': 5,
        'docker_container': 6,
        'file_operations': 7,
        'testing_automation': 8
      };

      const catPriorityA = categoryPriority[a.category] || 999;
      const catPriorityB = categoryPriority[b.category] || 999;

      return catPriorityA - catPriorityB;
    });
  }

  // ボタン数制限（UI負荷軽減）
  static limitButtons<T>(buttons: T[], maxButtons: number = 8): T[] {
    return buttons.slice(0, maxButtons);
  }
}