// DynamicCommandGenerator.ts - 入力テキストに基づく動的コマンド生成サービス
import { AutoGeneratedButtonConfig } from './DuplicateButtonFilter';

export interface InputAnalysis {
  frameworks: string[];
  technologies: string[];
  actions: string[];
  features: string[];
  complexity: 'beginner' | 'intermediate' | 'advanced';
  category: string;
}

export class DynamicCommandGenerator {

  // 入力テキストを解析
  static analyzeInput(inputText: string): InputAnalysis {
    const text = inputText.toLowerCase();

    // フレームワーク検出（日本語対応強化）
    const frameworks = [];

    // Web フレームワーク検出
    if (text.includes('flask') || text.includes('フラスク')) frameworks.push('flask');
    if (text.includes('fastapi')) frameworks.push('fastapi');
    if (text.includes('react') || text.includes('リアクト') || text.includes('react native') || text.includes('リアクトネイティブ')) frameworks.push('react');
    if (text.includes('vue') || text.includes('ビュー')) frameworks.push('vue');
    if (text.includes('django') || text.includes('ジャンゴ') || text.includes('管理画面')) frameworks.push('django');
    if (text.includes('express') || text.includes('エクスプレス')) frameworks.push('express');
    if (text.includes('streamlit') || text.includes('ストリームリット')) frameworks.push('streamlit');
    if (text.includes('next') || text.includes('ネクスト') || text.includes('サーバーサイドレンダリング') || text.includes('ssr')) frameworks.push('next');
    if (text.includes('nuxt') || text.includes('ナクスト')) frameworks.push('nuxt');
    if (text.includes('angular') || text.includes('アンギュラー')) frameworks.push('angular');
    if (text.includes('laravel') || text.includes('ララベル')) frameworks.push('laravel');
    if (text.includes('spring') || text.includes('スプリング')) frameworks.push('spring');
    if (text.includes('rails') || text.includes('レイルズ')) frameworks.push('rails');

    // データサイエンス・AI フレームワーク
    if (text.includes('tensorflow') || text.includes('テンソルフロー') || text.includes('深層学習')) frameworks.push('tensorflow');
    if (text.includes('pytorch') || text.includes('パイトーチ')) frameworks.push('pytorch');
    if (text.includes('scikit-learn') || text.includes('sklearn') || text.includes('機械学習') || text.includes('モデル訓練')) frameworks.push('scikit-learn');
    if (text.includes('pandas') || text.includes('パンダス') || text.includes('データクリーニング') || text.includes('前処理')) frameworks.push('pandas');
    if (text.includes('jupyter') || text.includes('ジュピター') || text.includes('notebook') || text.includes('ノートブック')) frameworks.push('jupyter');
    if (text.includes('matplotlib') || text.includes('マットプロット') || text.includes('可視化') || text.includes('グラフ')) frameworks.push('matplotlib');

    // モバイル開発
    if (text.includes('flutter') || text.includes('フラッター') || text.includes('クロスプラットフォーム')) frameworks.push('flutter');
    if (text.includes('expo') || text.includes('エクスポ')) frameworks.push('expo');
    if (text.includes('swiftui') || text.includes('スウィフトui') || text.includes('ios')) frameworks.push('swiftui');

    // バックエンド・API
    if (text.includes('graphql') || text.includes('グラフql')) frameworks.push('graphql');
    if (text.includes('microservices') || text.includes('マイクロサービス')) frameworks.push('microservices');

    // インフラ・DevOps
    if (text.includes('docker') || text.includes('ドッカー') || text.includes('コンテナ')) frameworks.push('docker');
    if (text.includes('kubernetes') || text.includes('k8s') || text.includes('クーバネティス') || text.includes('オーケストレーション')) frameworks.push('kubernetes');
    if (text.includes('terraform') || text.includes('テラフォーム') || text.includes('インフラ') || text.includes('コード化')) frameworks.push('terraform');

    // データベース
    if (text.includes('postgresql') || text.includes('postgres') || text.includes('ポストグレ')) frameworks.push('postgresql');
    if (text.includes('mongodb') || text.includes('モンゴ') || text.includes('nosql')) frameworks.push('mongodb');
    if (text.includes('redis') || text.includes('レディス') || text.includes('キャッシュ')) frameworks.push('redis');

    // Webアプリケーションパターン検出（日本語拡張）
    const webAppPatterns = [
      'webアプリ', 'web アプリ', 'ウェブアプリ', 'ウェブアプリケーション',
      'アプリケーション', 'webサイト', 'web サイト', 'ウェブサイト',
      'ホームページ', 'サイト', 'webページ', 'ウェブページ',
      'サーバー', 'api', 'アプリ', 'システム'
    ];

    const pythonHints = [
      'python', 'パイソン', 'シンプル', 'simple', 'hello world',
      '簡単', 'かんたん', '基本', '初歩'
    ];

    const hasWebPattern = webAppPatterns.some(pattern => text.includes(pattern));
    const hasPythonHint = pythonHints.some(hint => text.includes(hint));

    if (hasWebPattern && hasPythonHint && !frameworks.some(f => ['react', 'vue', 'angular'].includes(f))) {
      if (!frameworks.includes('flask')) frameworks.push('flask');
    }

    // 技術検出（日本語対応強化）
    const technologies = [];
    if (text.includes('python') || text.includes('パイソン')) technologies.push('python');
    if (text.includes('javascript') || text.includes('js') || text.includes('ジャバスクリプト')) technologies.push('javascript');
    if (text.includes('typescript') || text.includes('ts') || text.includes('タイプスクリプト')) technologies.push('typescript');
    if (text.includes('java') || text.includes('ジャバ') || text.includes('ジャヴァ')) technologies.push('java');
    if (text.includes('php') || text.includes('ピーエイチピー')) technologies.push('php');
    if (text.includes('go') || text.includes('golang') || text.includes('ゴー言語')) technologies.push('go');
    if (text.includes('rust') || text.includes('ラスト')) technologies.push('rust');
    if (text.includes('kotlin') || text.includes('コトリン')) technologies.push('kotlin');
    if (text.includes('swift') || text.includes('スウィフト')) technologies.push('swift');
    if (text.includes('node') || text.includes('ノード') || text.includes('nodejs')) technologies.push('nodejs');
    if (text.includes('docker') || text.includes('ドッカー')) technologies.push('docker');
    if (text.includes('kubernetes') || text.includes('k8s') || text.includes('クーバネティス')) technologies.push('kubernetes');
    if (text.includes('jupyter') || text.includes('ジュピター')) technologies.push('jupyter');
    if (text.includes('matplotlib') || text.includes('マットプロットリブ')) technologies.push('matplotlib');
    if (text.includes('データ') || text.includes('可視化') || text.includes('グラフ') || text.includes('チャート')) technologies.push('visualization');
    if (text.includes('ai') || text.includes('人工知能') || text.includes('機械学習') || text.includes('ml')) technologies.push('ai');
    if (text.includes('cicd') || text.includes('ci/cd') || text.includes('パイプライン')) technologies.push('cicd');
    if (text.includes('html') || text.includes('css') || text.includes('フロントエンド')) technologies.push('frontend');
    if (text.includes('spa') || text.includes('シングルページ')) technologies.push('spa');

    // アクション検出（日本語対応強化）
    const actions = [];
    if (text.includes('作成') || text.includes('作って') || text.includes('create') || text.includes('してください') ||
        text.includes('構築') || text.includes('開発') || text.includes('実装') || text.includes('作りたい')) actions.push('create');
    if (text.includes('起動') || text.includes('実行') || text.includes('start') || text.includes('run') ||
        text.includes('立ち上げ') || text.includes('スタート') || text.includes('動かし')) actions.push('start');
    if (text.includes('テスト') || text.includes('確認') || text.includes('test') || text.includes('検証') ||
        text.includes('試す') || text.includes('チェック')) actions.push('test');
    if (text.includes('デプロイ') || text.includes('deploy') || text.includes('配置') || text.includes('公開') ||
        text.includes('リリース')) actions.push('deploy');
    if (text.includes('インストール') || text.includes('install') || text.includes('導入') ||
        text.includes('セットアップ') || text.includes('設定')) actions.push('install');
    if (text.includes('停止') || text.includes('終了') || text.includes('stop') || text.includes('止める')) actions.push('stop');
    if (text.includes('更新') || text.includes('アップデート') || text.includes('update') || text.includes('修正')) actions.push('update');

    // 機能検出（日本語対応強化）
    const features = [];
    if (text.includes('hello world') || text.includes('ホームページ') || text.includes('トップページ') ||
        text.includes('メインページ') || text.includes('初期ページ') || text.includes('表紙')) features.push('homepage');
    if (text.includes('about') || text.includes('会社情報') || text.includes('企業情報') ||
        text.includes('アバウト') || text.includes('概要') || text.includes('詳細')) features.push('about');
    if (text.includes('api') || text.includes('エーピーアイ') || text.includes('接続') || text.includes('連携')) features.push('api');
    if (text.includes('データベース') || text.includes('database') || text.includes('db') ||
        text.includes('デービー') || text.includes('ストレージ')) features.push('database');
    if (text.includes('認証') || text.includes('auth') || text.includes('ログイン') || text.includes('サインイン') ||
        text.includes('ユーザー管理') || text.includes('アカウント')) features.push('auth');
    if (text.includes('検索') || text.includes('サーチ') || text.includes('search') ||
        text.includes('絞り込み') || text.includes('フィルター')) features.push('search');
    if (text.includes('チャット') || text.includes('メッセージ') || text.includes('コミュニケーション') ||
        text.includes('やり取り')) features.push('chat');
    if (text.includes('ブログ') || text.includes('記事') || text.includes('投稿') || text.includes('コンテンツ') ||
        text.includes('cms')) features.push('blog');
    if (text.includes('商品') || text.includes('製品') || text.includes('アイテム') || text.includes('カタログ') ||
        text.includes('一覧')) features.push('catalog');
    if (text.includes('決済') || text.includes('支払い') || text.includes('payment') || text.includes('課金') ||
        text.includes('購入')) features.push('payment');

    // 複雑度判定
    let complexity: 'beginner' | 'intermediate' | 'advanced' = 'beginner';
    if (frameworks.length > 1 || technologies.length > 2) complexity = 'intermediate';
    if (text.includes('advanced') || text.includes('複雑') || text.includes('machine learning')) complexity = 'advanced';

    // カテゴリ判定
    let category = 'web_app';
    if (technologies.includes('visualization')) category = 'data_visualization';
    if (text.includes('machine learning') || text.includes('ml')) category = 'machine_learning';
    if (technologies.includes('docker')) category = 'docker_container';

    return {
      frameworks,
      technologies,
      actions,
      features,
      complexity,
      category
    };
  }

  // Flask向けコマンド生成
  static generateFlaskCommands(analysis: InputAnalysis): AutoGeneratedButtonConfig[] {
    const commands: AutoGeneratedButtonConfig[] = [];
    const timestamp = new Date().toISOString();

    // 1. 依存関係インストール
    commands.push({
      id: `flask_install_${Date.now()}`,
      title: '🐍 Flask依存関係インストール',
      description: 'Flaskと必要なパッケージをインストールします',
      category: 'web_app',
      command: 'pip3 install Flask==2.3.3 Werkzeug==2.3.7',
      execution_type: 'python',
      button_config: {
        type: 'install',
        icon: '📦',
        color: '#4CAF50',
        gradient: ['#4CAF50', '#45a049'],
        priority: 1
      },
      local_metrics: {
        metrics: { confidence_score: 0.95 }
      },
      created_at: timestamp,
      source: 'dynamic_generator'
    });

    // 2. Flaskアプリ作成
    commands.push({
      id: `flask_create_${Date.now() + 1}`,
      title: '📝 Flaskアプリ作成',
      description: 'app.pyファイルを作成してFlaskアプリケーションを実装',
      category: 'web_app',
      command: `mkdir -p $TMPDIR/flask_app && cd $TMPDIR/flask_app && cat > app.py << 'EOF'
from flask import Flask
app = Flask(__name__)

@app.route('/')
def home():
    return '''
    <h1>Hello World!</h1>
    <p>シンプルなFlaskアプリケーションへようこそ！</p>
    <a href="/about">会社情報</a>
    '''

@app.route('/about')
def about():
    return '''
    <h1>会社情報</h1>
    <p>RemoteClaudeOPS Technology Solutions</p>
    <p>AI・Web開発・クラウドソリューション</p>
    <a href="/">ホーム</a>
    '''

if __name__ == '__main__':
    app.run(host='0.0.0.0', port=5001, debug=True)
EOF`,
      execution_type: 'bash',
      button_config: {
        type: 'create',
        icon: '📝',
        color: '#2196F3',
        gradient: ['#2196F3', '#1976D2'],
        priority: 2
      },
      local_metrics: {
        metrics: { confidence_score: 0.92 }
      },
      created_at: timestamp,
      source: 'dynamic_generator'
    });

    // 3. Flaskサーバー起動
    commands.push({
      id: `flask_start_${Date.now() + 2}`,
      title: '🚀 Flaskサーバー起動',
      description: 'Flaskアプリケーションを起動してWebサーバーを開始',
      category: 'web_app',
      command: 'cd $TMPDIR/flask_app && python3 app.py',
      execution_type: 'python',
      button_config: {
        type: 'start',
        icon: '🚀',
        color: '#FF9800',
        gradient: ['#FF9800', '#F57C00'],
        priority: 3
      },
      local_metrics: {
        metrics: { confidence_score: 0.90 }
      },
      created_at: timestamp,
      source: 'dynamic_generator'
    });

    // 4. ホームページ確認
    if (analysis.features.includes('homepage')) {
      commands.push({
        id: `flask_test_home_${Date.now() + 3}`,
        title: '🌐 ホームページ確認',
        description: 'Hello Worldページが正しく表示されるかテスト',
        category: 'web_app',
        command: 'curl -s http://localhost:5001/ || echo "サーバーが起動していません"',
        execution_type: 'bash',
        button_config: {
          type: 'test',
          icon: '🔍',
          color: '#9C27B0',
          gradient: ['#9C27B0', '#7B1FA2'],
          priority: 4
        },
        local_metrics: {
          metrics: { confidence_score: 0.88 }
        },
        created_at: timestamp,
        source: 'dynamic_generator'
      });
    }

    // 5. Aboutページ確認
    if (analysis.features.includes('about')) {
      commands.push({
        id: `flask_test_about_${Date.now() + 4}`,
        title: '🏢 会社情報ページ確認',
        description: '/aboutページが正しく表示されるかテスト',
        category: 'web_app',
        command: 'curl -s http://localhost:5001/about || echo "サーバーが起動していません"',
        execution_type: 'bash',
        button_config: {
          type: 'test',
          icon: '🏢',
          color: '#607D8B',
          gradient: ['#607D8B', '#455A64'],
          priority: 5
        },
        local_metrics: {
          metrics: { confidence_score: 0.85 }
        },
        created_at: timestamp,
        source: 'dynamic_generator'
      });
    }

    return commands;
  }

  // React向けコマンド生成
  static generateReactCommands(analysis: InputAnalysis): AutoGeneratedButtonConfig[] {
    const commands: AutoGeneratedButtonConfig[] = [];
    const timestamp = new Date().toISOString();

    commands.push({
      id: `react_create_${Date.now()}`,
      title: '⚛️ Reactアプリ作成',
      description: 'Create React Appでプロジェクトを初期化',
      category: 'web_app',
      command: 'npx create-react-app my-app && cd my-app',
      execution_type: 'bash',
      button_config: {
        type: 'create',
        icon: '⚛️',
        color: '#61DAFB',
        gradient: ['#61DAFB', '#21CBF3'],
        priority: 1
      },
      local_metrics: {
        metrics: { confidence_score: 0.93 }
      },
      created_at: timestamp,
      source: 'dynamic_generator'
    });

    commands.push({
      id: `react_start_${Date.now() + 1}`,
      title: '🚀 React開発サーバー起動',
      description: 'React開発サーバーを起動してアプリを表示',
      category: 'web_app',
      command: 'cd my-app && npm start',
      execution_type: 'bash',
      button_config: {
        type: 'start',
        icon: '🚀',
        color: '#FF9800',
        gradient: ['#FF9800', '#F57C00'],
        priority: 2
      },
      local_metrics: {
        metrics: { confidence_score: 0.90 }
      },
      created_at: timestamp,
      source: 'dynamic_generator'
    });

    return commands;
  }

  // データ可視化向けコマンド生成
  static generateDataVisualizationCommands(analysis: InputAnalysis): AutoGeneratedButtonConfig[] {
    const commands: AutoGeneratedButtonConfig[] = [];
    const timestamp = new Date().toISOString();

    commands.push({
      id: `matplotlib_install_${Date.now()}`,
      title: '📊 可視化ライブラリインストール',
      description: 'matplotlib, pandas, seabornをインストール',
      category: 'data_visualization',
      command: 'pip3 install matplotlib pandas seaborn numpy',
      execution_type: 'python',
      button_config: {
        type: 'install',
        icon: '📊',
        color: '#4CAF50',
        gradient: ['#4CAF50', '#45a049'],
        priority: 1
      },
      local_metrics: {
        metrics: { confidence_score: 0.94 }
      },
      created_at: timestamp,
      source: 'dynamic_generator'
    });

    commands.push({
      id: `plot_generate_${Date.now() + 1}`,
      title: '📈 サンプルプロット生成',
      description: 'matplotlib でサンプルグラフを生成',
      category: 'data_visualization',
      command: `python3 -c "
import matplotlib.pyplot as plt
import numpy as np
x = np.linspace(0, 10, 100)
y = np.sin(x)
plt.figure(figsize=(10, 6))
plt.plot(x, y, label='sin(x)')
plt.title('Sample Data Visualization')
plt.xlabel('X axis')
plt.ylabel('Y axis')
plt.legend()
plt.grid(True)
plt.savefig('$TMPDIR/sample_plot.png', dpi=300, bbox_inches='tight')
print('Plot saved to $TMPDIR/sample_plot.png')
"`,
      execution_type: 'python',
      button_config: {
        type: 'generate',
        icon: '📈',
        color: '#FF5722',
        gradient: ['#FF5722', '#D84315'],
        priority: 2
      },
      local_metrics: {
        metrics: { confidence_score: 0.91 }
      },
      created_at: timestamp,
      source: 'dynamic_generator'
    });

    return commands;
  }

  // メイン生成関数
  static generateCommandsFromInput(inputText: string): AutoGeneratedButtonConfig[] {
    console.log('🔍 DynamicCommandGenerator入力分析開始:', inputText);
    const analysis = this.analyzeInput(inputText);
    console.log('📊 分析結果:', {
      frameworks: analysis.frameworks,
      technologies: analysis.technologies,
      actions: analysis.actions,
      features: analysis.features,
      complexity: analysis.complexity,
      category: analysis.category
    });

    let commands: AutoGeneratedButtonConfig[] = [];

    // フレームワーク別コマンド生成
    if (analysis.frameworks.includes('flask')) {
      console.log('✅ Flask検出 -> Flaskコマンド生成実行');
      commands = commands.concat(this.generateFlaskCommands(analysis));
    }

    if (analysis.frameworks.includes('react')) {
      commands = commands.concat(this.generateReactCommands(analysis));
    }

    if (analysis.frameworks.includes('next')) {
      console.log('✅ Next.js検出 -> Next.jsコマンド生成実行');
      commands = commands.concat(this.generateNextCommands(analysis));
    }

    if (analysis.frameworks.includes('django')) {
      console.log('✅ Django検出 -> Djangoコマンド生成実行');
      commands = commands.concat(this.generateDjangoCommands(analysis));
    }

    if (analysis.frameworks.includes('tensorflow')) {
      console.log('✅ TensorFlow検出 -> TensorFlowコマンド生成実行');
      commands = commands.concat(this.generateTensorFlowCommands(analysis));
    }

    // カテゴリ別コマンド生成
    if (analysis.category === 'data_visualization') {
      commands = commands.concat(this.generateDataVisualizationCommands(analysis));
    }

    // 曖昧入力への推論処理
    if (commands.length === 0) {
      const inferences = this.inferFromAmbiguousInput(inputText);
      console.log('🤔 曖昧入力検出 -> 推論実行:', inferences);

      if (inferences.includes('flask')) {
        console.log('💡 Flask推論適用');
        const flaskAnalysis = { ...analysis, frameworks: ['flask'] };
        commands = commands.concat(this.generateFlaskCommands(flaskAnalysis));
      }

      if (inferences.includes('matplotlib')) {
        console.log('💡 データ可視化推論適用');
        const vizAnalysis = { ...analysis, category: 'data_visualization' };
        commands = commands.concat(this.generateDataVisualizationCommands(vizAnalysis));
      }
    }

    // 汎用コマンド追加
    if (commands.length === 0) {
      commands.push({
        id: `generic_help_${Date.now()}`,
        title: '❓ ヘルプ・ガイダンス',
        description: '入力内容に基づく推奨アクションを表示',
        category: 'general',
        command: `echo "入力内容: ${inputText.substring(0, 50)}..." && echo "検出された要素:" && echo "- フレームワーク: ${analysis.frameworks.join(', ') || 'なし'}" && echo "- 技術: ${analysis.technologies.join(', ') || 'なし'}" && echo "- アクション: ${analysis.actions.join(', ') || 'なし'}"`,
        execution_type: 'bash',
        button_config: {
          type: 'info',
          icon: '❓',
          color: '#666666',
          gradient: ['#666666', '#555555'],
          priority: 999
        },
        local_metrics: {
          metrics: { confidence_score: 0.70 }
        },
        created_at: new Date().toISOString(),
        source: 'dynamic_generator'
      });
    }

    return commands;
  }

  // Next.js向けコマンド生成
  static generateNextCommands(analysis: InputAnalysis): AutoGeneratedButtonConfig[] {
    const commands: AutoGeneratedButtonConfig[] = [];
    const timestamp = new Date().toISOString();

    commands.push({
      id: `next_create_${Date.now()}`,
      title: '⚡ Next.jsプロジェクト作成',
      description: 'Next.jsでSSRアプリケーションを作成',
      category: 'web_app',
      command: 'npx create-next-app@latest my-next-app --typescript --tailwind --app',
      execution_type: 'bash',
      button_config: {
        type: 'create',
        icon: '⚡',
        color: '#000000',
        priority: 1
      },
      local_metrics: { metrics: { confidence_score: 0.90 } },
      created_at: timestamp,
      source: 'dynamic_generator'
    });

    commands.push({
      id: `next_dev_${Date.now() + 1}`,
      title: '🚀 Next.js開発サーバー起動',
      description: '開発サーバーを起動してSSRを確認',
      category: 'web_app',
      command: 'cd my-next-app && npm run dev',
      execution_type: 'bash',
      button_config: {
        type: 'start',
        icon: '🚀',
        color: '#0070f3',
        priority: 2
      },
      local_metrics: { metrics: { confidence_score: 0.88 } },
      created_at: timestamp,
      source: 'dynamic_generator'
    });

    return commands;
  }

  // Django向けコマンド生成
  static generateDjangoCommands(analysis: InputAnalysis): AutoGeneratedButtonConfig[] {
    const commands: AutoGeneratedButtonConfig[] = [];
    const timestamp = new Date().toISOString();

    commands.push({
      id: `django_install_${Date.now()}`,
      title: '🐍 Django依存関係インストール',
      description: 'Djangoフレームワークをインストール',
      category: 'web_app',
      command: 'pip3 install Django==4.2.7',
      execution_type: 'bash',
      button_config: {
        type: 'install',
        icon: '📦',
        color: '#092e20',
        priority: 1
      },
      local_metrics: { metrics: { confidence_score: 0.92 } },
      created_at: timestamp,
      source: 'dynamic_generator'
    });

    commands.push({
      id: `django_create_${Date.now() + 1}`,
      title: '🏗️ Djangoプロジェクト作成',
      description: 'Djangoプロジェクトを初期化',
      category: 'web_app',
      command: 'mkdir -p $TMPDIR/django_project && cd $TMPDIR/django_project && django-admin startproject myproject .',
      execution_type: 'bash',
      button_config: {
        type: 'create',
        icon: '🏗️',
        color: '#092e20',
        priority: 2
      },
      local_metrics: { metrics: { confidence_score: 0.90 } },
      created_at: timestamp,
      source: 'dynamic_generator'
    });

    commands.push({
      id: `django_migrate_${Date.now() + 2}`,
      title: '🗄️ データベースマイグレーション',
      description: 'データベースを初期化',
      category: 'web_app',
      command: 'cd $TMPDIR/django_project && python manage.py migrate',
      execution_type: 'bash',
      button_config: {
        type: 'setup',
        icon: '🗄️',
        color: '#092e20',
        priority: 3
      },
      local_metrics: { metrics: { confidence_score: 0.88 } },
      created_at: timestamp,
      source: 'dynamic_generator'
    });

    commands.push({
      id: `django_admin_${Date.now() + 3}`,
      title: '👤 管理ユーザー作成',
      description: 'Django管理画面用のスーパーユーザーを作成',
      category: 'web_app',
      command: 'cd $TMPDIR/django_project && echo "from django.contrib.auth import get_user_model; User = get_user_model(); User.objects.create_superuser(\\"admin\\", \\"admin@example.com\\", \\"admin123\\")" | python manage.py shell',
      execution_type: 'bash',
      button_config: {
        type: 'setup',
        icon: '👤',
        color: '#092e20',
        priority: 4
      },
      local_metrics: { metrics: { confidence_score: 0.85 } },
      created_at: timestamp,
      source: 'dynamic_generator'
    });

    commands.push({
      id: `django_run_${Date.now() + 4}`,
      title: '🚀 Djangoサーバー起動',
      description: '開発サーバーを起動して管理画面を確認',
      category: 'web_app',
      command: 'cd $TMPDIR/django_project && python manage.py runserver 0.0.0.0:8000',
      execution_type: 'bash',
      button_config: {
        type: 'start',
        icon: '🚀',
        color: '#092e20',
        priority: 5
      },
      local_metrics: { metrics: { confidence_score: 0.90 } },
      created_at: timestamp,
      source: 'dynamic_generator'
    });

    return commands;
  }

  // TensorFlow向けコマンド生成
  static generateTensorFlowCommands(analysis: InputAnalysis): AutoGeneratedButtonConfig[] {
    const commands: AutoGeneratedButtonConfig[] = [];
    const timestamp = new Date().toISOString();

    commands.push({
      id: `tf_install_${Date.now()}`,
      title: '🧠 TensorFlow環境構築',
      description: 'TensorFlowと依存ライブラリをインストール',
      category: 'machine_learning',
      command: 'pip3 install tensorflow==2.13.0 numpy pandas matplotlib',
      execution_type: 'bash',
      button_config: {
        type: 'install',
        icon: '📦',
        color: '#FF6F00',
        priority: 1
      },
      local_metrics: { metrics: { confidence_score: 0.92 } },
      created_at: timestamp,
      source: 'dynamic_generator'
    });

    commands.push({
      id: `tf_sample_${Date.now() + 1}`,
      title: '🤖 深層学習サンプル作成',
      description: 'TensorFlowで基本的なニューラルネットワークを作成',
      category: 'machine_learning',
      command: `mkdir -p $TMPDIR/tensorflow_app && cd $TMPDIR/tensorflow_app && cat > deep_learning_sample.py << 'EOF'
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt

print("🧠 TensorFlow Deep Learning Sample")
print("=" * 50)

# Generate sample data
X = np.random.randn(1000, 2)
y = (X[:, 0] + X[:, 1] > 0).astype(int)

# Create model
model = tf.keras.Sequential([
    tf.keras.layers.Dense(10, activation='relu', input_shape=(2,)),
    tf.keras.layers.Dense(5, activation='relu'),
    tf.keras.layers.Dense(1, activation='sigmoid')
])

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

print("Training model...")
history = model.fit(X, y, epochs=50, validation_split=0.2, verbose=0)

loss, accuracy = model.evaluate(X, y, verbose=0)
print(f"Final accuracy: {accuracy:.2%}")

plt.figure(figsize=(12, 4))
plt.subplot(1, 2, 1)
plt.plot(history.history['loss'], label='Training Loss')
plt.plot(history.history['val_loss'], label='Validation Loss')
plt.title('Model Loss')
plt.legend()

plt.subplot(1, 2, 2)
plt.plot(history.history['accuracy'], label='Training Accuracy')
plt.plot(history.history['val_accuracy'], label='Validation Accuracy')
plt.title('Model Accuracy')
plt.legend()

plt.tight_layout()
plt.savefig('training_history.png')
print("Training history saved as training_history.png")
EOF`,
      execution_type: 'bash',
      button_config: {
        type: 'create',
        icon: '🤖',
        color: '#FF6F00',
        priority: 2
      },
      local_metrics: { metrics: { confidence_score: 0.88 } },
      created_at: timestamp,
      source: 'dynamic_generator'
    });

    commands.push({
      id: `tf_run_${Date.now() + 2}`,
      title: '🚀 深層学習モデル実行',
      description: 'ニューラルネットワークを訓練して結果を表示',
      category: 'machine_learning',
      command: 'cd $TMPDIR/tensorflow_app && python3 deep_learning_sample.py',
      execution_type: 'bash',
      button_config: {
        type: 'start',
        icon: '🚀',
        color: '#FF6F00',
        priority: 3
      },
      local_metrics: { metrics: { confidence_score: 0.85 } },
      created_at: timestamp,
      source: 'dynamic_generator'
    });

    return commands;
  }

  // 入力テキストからカテゴリを推定
  static inferCategory(inputText: string): string {
    const analysis = this.analyzeInput(inputText);
    return analysis.category;
  }

  // 曖昧入力推論強化
  static inferFromAmbiguousInput(inputText: string): string[] {
    const text = inputText.toLowerCase();
    const inferences = [];

    // Web関連推論
    if ((text.includes('web') || text.includes('サイト') || text.includes('簡単')) &&
        !text.includes('react') && !text.includes('vue')) {
      inferences.push('flask');
    }

    // 学習目的推論
    if (text.includes('勉強') || text.includes('学習') || text.includes('練習')) {
      inferences.push('flask');
    }

    // データ分析推論
    if (text.includes('データ') && text.includes('分析')) {
      inferences.push('matplotlib');
    }

    return inferences;
  }

  // 信頼度スコア計算
  static calculateConfidenceScore(inputText: string, commandType: string): number {
    const analysis = this.analyzeInput(inputText);
    let score = 0.5; // ベーススコア

    // フレームワーク一致
    if (commandType.includes('flask') && analysis.frameworks.includes('flask')) score += 0.3;
    if (commandType.includes('react') && analysis.frameworks.includes('react')) score += 0.3;
    if (commandType.includes('next') && analysis.frameworks.includes('next')) score += 0.3;
    if (commandType.includes('django') && analysis.frameworks.includes('django')) score += 0.3;
    if (commandType.includes('tensorflow') && analysis.frameworks.includes('tensorflow')) score += 0.3;

    // アクション一致
    if (commandType.includes('install') && analysis.actions.includes('install')) score += 0.2;
    if (commandType.includes('start') && analysis.actions.includes('start')) score += 0.2;
    if (commandType.includes('create') && analysis.actions.includes('create')) score += 0.2;

    return Math.min(score, 1.0);
  }
}