import React, { useState, useEffect, useRef } from 'react';
import {
  View,
  Text,
  StyleSheet,
  SafeAreaView,
  TouchableOpacity,
  ScrollView,
  Image,
  Alert,
  ActivityIndicator,
  Modal,
  Dimensions,
  RefreshControl,
  FlatList,
  TextInput,
} from 'react-native';
import { WebView } from 'react-native-webview';
import EnhancedWebSocketService from '../services/EnhancedWebSocketService';
import LocalMetricsService from '../services/LocalMetricsService';
import CommandExecutionButton from '../components/CommandExecutionButton';
import AutoGeneratedButton from '../components/AutoGeneratedButton';
import { DuplicateButtonFilter } from '../services/DuplicateButtonFilter';
import { WebAppDetectionService, WebAppHelpers } from '../services/WebAppDetectionService';
import { DynamicCommandGenerator } from '../services/DynamicCommandGenerator';
import EnhancedPreviewAccuracyService from '../services/EnhancedPreviewAccuracyService';
import ClaudeCodeAgentService from '../services/ClaudeCodeAgentService';
import UnifiedPreviewDetectionService from '../services/UnifiedPreviewDetectionService';

interface CommandConfig {
  id: string;
  name: string;
  description: string;
  command: string;
  type: 'python' | 'matplotlib' | 'web_server' | 'docker' | 'jupyter';
  category: string;
  expected_output: string;
  execution_time: string;
  difficulty: 'beginner' | 'intermediate' | 'advanced';
}

interface PreviewItem {
  id: string;
  type: 'matplotlib' | 'webapp' | 'notebook';
  name: string;
  description: string;
  status: 'ready' | 'running' | 'error';
  path?: string;
  port?: number;
  url?: string;
  size?: string;
  timestamp?: string;
  process?: string;
}

interface Props {
  route: {
    params: {
      serverUrl: string;
      projectId: string;
      projectName?: string;
    };
  };
  navigation: any;
}

const { width: screenWidth, height: screenHeight } = Dimensions.get('window');

const EnhancedPreviewScreen: React.FC<Props> = ({ route, navigation }) => {
  const { serverUrl, projectId, projectName } = route.params;
  const [isConnected, setIsConnected] = useState(false);
  const [previewItems, setPreviewItems] = useState<PreviewItem[]>([]);
  const [selectedItem, setSelectedItem] = useState<PreviewItem | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [refreshing, setRefreshing] = useState(false);
  const [showFullscreen, setShowFullscreen] = useState(false);
  const [activeTab, setActiveTab] = useState<'commands' | 'all' | 'matplotlib' | 'webapp' | 'notebook' | 'metrics'>('commands');
  const [imageData, setImageData] = useState<string | null>(null);
  const [webAppUrl, setWebAppUrl] = useState<string | null>(null);

  // W&B統合関連の状態
  const [localMetricsService] = useState(() => LocalMetricsService.getInstance());
  const [metricsConnected, setMetricsConnected] = useState<boolean>(true);
  const [showMetricsModal, setShowMetricsModal] = useState<boolean>(false);
  const [commands, setCommands] = useState<CommandConfig[]>([]);
  const [filteredCommands, setFilteredCommands] = useState<CommandConfig[]>([]);
  const [commandCategory, setCommandCategory] = useState<string>('all');
  const [isExecutingCommand, setIsExecutingCommand] = useState<boolean>(false);
  const [autoGeneratedButtons, setAutoGeneratedButtons] = useState<any[]>([]);
  const [detectedWebApps, setDetectedWebApps] = useState<any[]>([]);
  const [dynamicCommands, setDynamicCommands] = useState<any[]>([]);
  const [lastInputText, setLastInputText] = useState<string>('');
  const [accuracyService] = useState(() => EnhancedPreviewAccuracyService.getInstance());
  const [agentService] = useState(() => ClaudeCodeAgentService.getInstance());
  const [unifiedDetectionService] = useState(() => UnifiedPreviewDetectionService.getInstance());
  const [currentAccuracyScore, setCurrentAccuracyScore] = useState(0);
  const [isAIOptimizing, setIsAIOptimizing] = useState(false);

  useEffect(() => {
    connectToServer();
    initializeLocalMetrics();
    loadCommands();

    // 初期状態では動的コマンドは空で開始
    setDynamicCommands([]);

    // 🚀 新しい精度向上システム初期化
    initializeAccuracyServices();

    return () => {
      EnhancedWebSocketService.unregisterScreenCallbacks('preview');
      WebAppDetectionService.stopPortMonitoring();
      WebAppDetectionService.cleanupOldApps();
      unifiedDetectionService.stopUnifiedDetection();
    };
  }, []);

  // W&B状態の更新
  useEffect(() => {
    const updateMetricsState = () => {
      setMetricsConnected(true); // ローカルメトリクスは常に利用可能
    };

    updateMetricsState();
    const interval = setInterval(updateMetricsState, 5000); // 5秒ごとに更新

    return () => clearInterval(interval);
  }, [localMetricsService]);

  // Filter commands when commands or category changes with duplicate removal
  useEffect(() => {
    // 動的コマンドを既存のコマンド形式に変換
    const dynamicAsCommands = dynamicCommands.map(dynCmd => ({
      id: dynCmd.id || `dynamic_${Date.now()}_${Math.random()}`,
      name: dynCmd.title || dynCmd.name || 'Dynamic Command',
      description: dynCmd.description || 'Dynamically generated command',
      command: dynCmd.command || 'echo "Dynamic command"',
      type: (dynCmd.execution_type || dynCmd.type || 'python') as 'python' | 'matplotlib' | 'web_server' | 'docker' | 'jupyter',
      category: dynCmd.category || 'dynamic',
      expected_output: dynCmd.expected_output || 'Dynamic command execution result',
      execution_time: dynCmd.execution_time || '2-5秒',
      difficulty: (dynCmd.difficulty || 'beginner') as const
    }));

    // 動的コマンドが存在する場合は動的コマンドのみを使用、そうでなければ既存コマンドを使用
    let commandsToUse;
    if (dynamicCommands.length > 0) {
      commandsToUse = dynamicAsCommands;
      console.log('🔄 Using dynamic commands:', dynamicCommands.length, 'commands:', dynamicAsCommands.map(cmd => cmd.name));
    } else {
      let filteredCmds = commands;
      if (commandCategory !== 'all') {
        filteredCmds = commands.filter(cmd => cmd.category === commandCategory);
      }
      commandsToUse = filteredCmds;
      console.log('📚 Using static commands:', filteredCmds.length, 'category:', commandCategory);
    }

    const allCommands = commandsToUse;

    // 動的コマンドの場合は重複除去をスキップ（既にDynamicCommandGeneratorで適切なIDが設定されている）
    let finalCommands;
    if (dynamicCommands.length > 0) {
      // 動的コマンドは既にユニークなIDで生成されているため、直接使用
      finalCommands = dynamicAsCommands;
      console.log('🔄 Using dynamic commands without duplicate filtering:', finalCommands.length);
    } else {
      // 静的コマンドの場合のみ重複除去を適用
      const uniqueCommands = DuplicateButtonFilter.removeDuplicateAutoButtons(
        allCommands.map(cmd => ({
          id: cmd.id,
          title: cmd.name,
          description: cmd.description,
          command: cmd.command,
          execution_type: cmd.type,
          category: cmd.category,
          button_config: {
            type: 'default',
            icon: '⚙️',
            color: '#666666',
            gradient: ['#666666', '#555555'],
            priority: 999
          },
          local_metrics: { metrics: { confidence_score: 0.5 } },
          created_at: new Date().toISOString(),
          source: 'static'
        }))
      );

      finalCommands = uniqueCommands.map(unique => {
        const originalCmd = allCommands.find(cmd => cmd.id === unique.id);
        return originalCmd || {
          id: unique.id,
          name: unique.title,
          description: unique.description,
          command: unique.command,
          type: unique.execution_type as 'python' | 'matplotlib' | 'web_server' | 'docker' | 'jupyter',
          category: unique.category,
          expected_output: 'Static command execution result',
          execution_time: '2-5秒',
          difficulty: 'beginner' as const
        };
      });
      console.log('📚 Using static commands with duplicate filtering:', finalCommands.length);
    }

    console.log('🎯 Final filtered commands:', finalCommands.length, 'commands:', finalCommands.map(cmd => cmd.name));
    setFilteredCommands(finalCommands);
  }, [commands, commandCategory, dynamicCommands]);

  const connectToServer = async () => {
    try {
      setIsLoading(true);

      const success = await EnhancedWebSocketService.connect(serverUrl);
      if (success) {
        setIsConnected(true);

        EnhancedWebSocketService.registerScreenCallbacks('preview', {
          onMessage: handleServerMessage,
          onConnect: () => {
            setIsConnected(true);
            requestPreviewList();
            // Start web app monitoring
            WebAppDetectionService.startPortMonitoring(5000);
          },
          onDisconnect: () => {
            setIsConnected(false);
            // Stop web app monitoring
            WebAppDetectionService.stopPortMonitoring();
          },
          onError: (error) => {
            console.error('WebSocket error:', error);
            Alert.alert('Connection Error', 'Failed to connect to server');
          },
        }, 3);

        requestPreviewList();
      } else {
        Alert.alert('Connection Failed', 'Could not connect to server');
      }
    } catch (error) {
      console.error('Connection error:', error);
      Alert.alert('Error', 'Failed to establish connection');
    } finally {
      setIsLoading(false);
    }
  };

  const requestPreviewList = () => {
    if (!isConnected) return;

    EnhancedWebSocketService.send({
      type: 'preview_list_request',
      data: {
        project_id: projectId,
      }
    });
  };

  const handleServerMessage = (message: any) => {
    console.log('Preview message received:', message.type, message.data);

    switch (message.type) {
      case 'preview_list_response':
        if (message.data.previews) {
          // Filter duplicates and merge with detected web apps
          const serverPreviews = message.data.previews || [];
          const webAppPreviews = WebAppDetectionService.getDetectedApps()
            .map(app => WebAppHelpers.formatForPreview(app));

          // Remove duplicates by comparing ports for web apps
          const uniquePreviews = [...serverPreviews];
          webAppPreviews.forEach(webApp => {
            const exists = serverPreviews.some(preview =>
              preview.type === 'webapp' && preview.port === webApp.port
            );
            if (!exists) {
              uniquePreviews.push({
                id: webApp.id,
                type: webApp.type,
                name: webApp.name,
                description: webApp.description,
                status: webApp.status,
                port: webApp.port,
                url: webApp.url,
                timestamp: webApp.timestamp
              });
            }
          });

          setPreviewItems(uniquePreviews);
        }
        break;

      case 'preview_image_response':
        if (message.data.image_data) {
          setImageData(message.data.image_data);
          setShowFullscreen(true);
        }
        break;

      case 'preview_webapp_response':
        if (message.data.url) {
          setWebAppUrl(message.data.url);
          setShowFullscreen(true);
        }
        break;

      case 'command_execution_result':
        handleCommandExecutionResult(message.data);
        break;

      case 'matplotlib_generated':
        handleMatplotlibGenerated(message.data);
        break;

      case 'error':
        Alert.alert('Error', message.data.message || 'Unknown error occurred');
        break;
    }
  };

  const refreshPreviews = async () => {
    setRefreshing(true);
    requestPreviewList();
    setTimeout(() => setRefreshing(false), 1000);
  };

  const openPreviewItem = (item: PreviewItem) => {
    setSelectedItem(item);

    if (item.type === 'matplotlib') {
      // Request image data
      EnhancedWebSocketService.send({
        type: 'preview_get_image',
        data: {
          project_id: projectId,
          image_path: item.path,
        }
      });
    } else if (item.type === 'webapp') {
      // Request webapp info
      EnhancedWebSocketService.send({
        type: 'preview_get_webapp',
        data: {
          project_id: projectId,
          port: item.port,
        }
      });
    } else if (item.type === 'notebook') {
      // Open Jupyter in fullscreen
      setWebAppUrl(item.url || `http://localhost:${item.port}`);
      setShowFullscreen(true);
    }

    // W&B統合: Matplotlibプロットを自動でW&Bにログ
    if (item.type === 'matplotlib' && currentExperiment) {
      integrateWithLocalMetrics(item);
    }
  };

  const closeFullscreen = () => {
    setShowFullscreen(false);
    setImageData(null);
    setWebAppUrl(null);
    setSelectedItem(null);
  };

  // 動的コマンド生成機能
  const generateDynamicCommands = (inputText: string) => {
    if (!inputText || inputText.trim().length === 0) {
      setDynamicCommands([]);
      return;
    }

    try {
      console.log('🔄 動的コマンド生成開始 [FIXED]:', inputText);
      const dynamicButtons = DynamicCommandGenerator.generateCommandsFromInput(inputText);

      // DynamicCommandGeneratorは既にユニークなIDを持つコマンドを生成するため、重複除去をスキップ
      console.log('✅ 動的コマンド生成完了:', dynamicButtons.length, 'コマンド');
      console.log('📋 生成されたコマンド:', dynamicButtons.map(cmd => ({ id: cmd.id, title: cmd.title })));
      setDynamicCommands(dynamicButtons);
      setLastInputText(inputText);
    } catch (error) {
      console.error('❌ 動的コマンド生成エラー:', error);
      setDynamicCommands([]);
    }
  };

  // Enhanced Commands loading with dynamic categorization
  const loadCommands = async () => {
    try {
      // Try to load enhanced Japanese commands from server
      const enhancedCommands = await loadEnhancedCommands();
      if (enhancedCommands.length > 0) {
        setCommands(enhancedCommands);
        return;
      }
    } catch (error) {
      console.log('Enhanced commands not available, using default commands');
    }

    // Fallback to default commands
    const demoCommands: CommandConfig[] = [
      {
        id: "python_hello",
        name: "🐍 Python Hello World",
        description: "シンプルなPython Hello Worldプログラムを実行",
        command: "python3 -c \"print('Hello from RemoteClaudeOPS v4.0!')\"",
        type: "python",
        category: "basic",
        expected_output: "Hello from RemoteClaudeOPS v4.0!",
        execution_time: "1-2秒",
        difficulty: "beginner"
      },
      {
        id: "matplotlib_demo",
        name: "📊 W&B統合データ可視化",
        description: "CNN分析結果をmatplotlibでプロット生成",
        command: "python3 -c \"import matplotlib.pyplot as plt; import numpy as np; x=np.linspace(0,10,100); y=np.sin(x); plt.plot(x,y); plt.title('W&B CNN Analysis Demo'); plt.savefig('/tmp/demo_plot.png'); print('Plot saved to /tmp/demo_plot.png')\"",
        type: "matplotlib",
        category: "visualization",
        expected_output: "Plot saved to /tmp/demo_plot.png",
        execution_time: "3-5秒",
        difficulty: "intermediate"
      },
      {
        id: "web_server",
        name: "🌐 Webサーバー起動",
        description: "簡単なHTTPサーバーを起動してWebアプリケーションをテスト",
        command: "python3 -m http.server 8000 --directory /tmp &",
        type: "web_server",
        category: "server",
        expected_output: "Serving HTTP on 0.0.0.0 port 8000",
        execution_time: "即座",
        difficulty: "beginner"
      },
      {
        id: "docker_status",
        name: "🐳 Docker状態確認",
        description: "現在のDockerコンテナとイメージの状態を確認",
        command: "docker ps -a && echo '--- Images ---' && docker images",
        type: "docker",
        category: "system",
        expected_output: "Container and image listings",
        execution_time: "2-3秒",
        difficulty: "intermediate"
      },
      {
        id: "jupyter_launch",
        name: "📔 Jupyter Notebook起動",
        description: "Jupyter Notebookサーバーを起動してインタラクティブ環境を提供",
        command: "jupyter notebook --ip=0.0.0.0 --port=8888 --no-browser --allow-root &",
        type: "jupyter",
        category: "interactive",
        expected_output: "Jupyter server running on http://0.0.0.0:8888",
        execution_time: "5-10秒",
        difficulty: "advanced"
      }
    ];
    setCommands(demoCommands);
  };

  // Enhanced command loading from server
  const loadEnhancedCommands = async (): Promise<CommandConfig[]> => {
    try {
      // Mock enhanced commands (in real app, this would fetch from server)
      const enhancedCommands: CommandConfig[] = [
        {
          id: "japanese_text_processing",
          name: "📝 日本語テキスト処理",
          description: "MeCab形態素解析を使用した日本語テキスト分析",
          command: "python3 -c \"print('日本語テキスト処理デモ: こんにちは、世界！')\"",
          type: "python",
          category: "nlp",
          expected_output: "形態素解析された日本語テキスト",
          execution_time: "2-3秒",
          difficulty: "intermediate"
        },
        {
          id: "japanese_chart_visualization",
          name: "📊 日本語グラフ可視化",
          description: "日本語ラベル付きのグラフを生成",
          command: "python3 -c \"import matplotlib.pyplot as plt; import numpy as np; categories = ['売上', '利益', '費用', '投資']; values = [100, 80, 60, 40]; plt.figure(figsize=(10, 6)); plt.bar(categories, values, color=['#FF6B6B', '#4ECDC4', '#45B7D1', '#96CEB4']); plt.title('2024年度 財務データ分析', fontsize=16); plt.xlabel('項目'); plt.ylabel('金額 (百万円)'); plt.grid(True, alpha=0.3); plt.tight_layout(); plt.savefig('/tmp/japanese_chart.png', dpi=300, bbox_inches='tight'); print('日本語チャートを保存しました: /tmp/japanese_chart.png')\"",
          type: "matplotlib",
          category: "visualization",
          expected_output: "日本語ラベル付きグラフ画像",
          execution_time: "3-5秒",
          difficulty: "intermediate"
        },
        {
          id: "multiagent_worker_api",
          name: "🤖 マルチエージェントWorker API",
          description: "複数のAIエージェントが協調動作するWorker APIシステム",
          command: "python3 -c \"import json; import time; import threading; from datetime import datetime; print('🤖 マルチエージェントWorker API起動'); print('✅ エージェント協調処理完了')\"",
          type: "python",
          category: "multiagent",
          expected_output: "マルチエージェント協調処理結果",
          execution_time: "6-8秒",
          difficulty: "advanced"
        },
        {
          id: "data_science_pipeline",
          name: "📈 データサイエンスパイプライン",
          description: "機械学習パイプライン全体を実行（データ前処理→学習→評価→可視化）",
          command: "python3 -c \"import numpy as np; import matplotlib.pyplot as plt; print('📊 データサイエンスパイプライン開始'); print('✅ パイプライン完了: 精度 87.5%')\"",
          type: "matplotlib",
          category: "machine_learning",
          expected_output: "機械学習パイプライン結果と可視化",
          execution_time: "8-12秒",
          difficulty: "advanced"
        },
        {
          id: "realtime_dashboard",
          name: "📊 リアルタイムダッシュボード",
          description: "WebSocketを使用したリアルタイムデータダッシュボード",
          command: "python3 -c \"print('📊 リアルタイムダッシュボード起動'); print('🌐 ダッシュボード: http://localhost:8080')\"",
          type: "web_server",
          category: "realtime",
          expected_output: "リアルタイムダッシュボード起動",
          execution_time: "5-7秒",
          difficulty: "advanced"
        }
      ];

      return enhancedCommands;
    } catch (error) {
      console.error('Failed to load enhanced commands:', error);
      return [];
    }
  };

  // W&B初期化
  const initializeWandB = async () => {
    try {
      // デモ用のダミーAPIキーで初期化
      await wandbService.initialize('demo_api_key_' + Date.now());
      console.log('W&B integration initialized');
    } catch (error) {
      console.error('Failed to initialize W&B:', error);
    }
  };

  // MatplotlibプロットのW&B統合
  const integrateWithWandB = async (previewItem: PreviewItem) => {
    try {
      if (previewItem.type === 'matplotlib' && currentExperiment) {
        // プロットをW&Bに統合
        const plotData = wandbService.convertPreviewToWandB({
          title: previewItem.name,
          content: imageData, // base64データ
          type: 'matplotlib',
          metadata: {
            timestamp: new Date().toISOString(),
            projectId: projectId,
          },
        });

        if (plotData) {
          await wandbService.logPlot(
            previewItem.name,
            plotData.data,
            imageData || undefined
          );
          console.log(`Plot integrated with W&B: ${previewItem.name}`);
        }
      }
    } catch (error) {
      console.error('Failed to integrate with W&B:', error);
    }
  };

  // W&B実験を開始
  const startWandBExperiment = async () => {
    try {
      const experiment = await wandbService.startExperiment(
        `Preview_Experiment_${Date.now()}`,
        projectId || 'remote_claude_preview',
        {
          project_id: projectId,
          timestamp: new Date().toISOString(),
        }
      );

      if (experiment) {
        console.log('W&B experiment started:', experiment.name);
        setCurrentExperiment(experiment);
      }
    } catch (error) {
      console.error('Failed to start W&B experiment:', error);
    }
  };

  // W&B実験を終了
  const finishWandBExperiment = async () => {
    try {
      if (currentExperiment) {
        await wandbService.finishExperiment(currentExperiment.id);
        console.log('W&B experiment finished:', currentExperiment.name);
        setCurrentExperiment(null);
      }
    } catch (error) {
      console.error('Failed to finish W&B experiment:', error);
    }
  };

  // Command execution
  const executeCommand = async (command: CommandConfig) => {
    try {
      setIsExecutingCommand(true);

      EnhancedWebSocketService.send({
        type: 'execute_command',
        data: {
          project_id: projectId,
          command: command.command,
          command_type: command.type,
          command_id: command.id,
          command_name: command.name,
        }
      });

      return new Promise<{ success: boolean; output?: string; error?: string }>((resolve) => {
        const timeout = setTimeout(() => {
          setIsExecutingCommand(false);
          resolve({ success: false, error: 'Command execution timeout' });
        }, 30000);

        const messageHandler = (message: any) => {
          if (message.type === 'command_execution_result' && message.data?.command_id === command.id) {
            clearTimeout(timeout);
            setIsExecutingCommand(false);
            EnhancedWebSocketService.unregisterCallback('command_execution_result', messageHandler);

            if (message.data.success) {
              resolve({ success: true, output: message.data.output });
            } else {
              resolve({ success: false, error: message.data.error });
            }
          }
        };

        EnhancedWebSocketService.registerCallback('command_execution_result', messageHandler);
      });
    } catch (error) {
      setIsExecutingCommand(false);
      return { success: false, error: error.message || 'Unknown error' };
    }
  };

  // Handle command execution results with web app detection
  const handleCommandExecutionResult = (data: any) => {
    if (data.success && data.type === 'matplotlib' && data.image_data) {
      handleMatplotlibGenerated(data);
    }

    // Web app detection from command output
    if (data.success && data.output) {
      const detectedWebApp = WebAppDetectionService.detectWebAppFromOutput(
        data.output,
        data.command || ''
      );

      if (detectedWebApp) {
        console.log('🌐 Web app detected from command output:', detectedWebApp);
        WebAppDetectionService.registerWebApp(detectedWebApp);

        // Add to preview items
        const webAppPreviewItem: PreviewItem = {
          id: `webapp_${detectedWebApp.port}_${Date.now()}`,
          type: 'webapp',
          name: `${detectedWebApp.type.toUpperCase()} Server`,
          description: `${detectedWebApp.type} application running on port ${detectedWebApp.port}`,
          status: detectedWebApp.status === 'running' ? 'ready' : 'error',
          port: detectedWebApp.port,
          url: detectedWebApp.url,
          timestamp: detectedWebApp.detectedAt.toLocaleString(),
          process: detectedWebApp.type
        };

        setPreviewItems(prev => {
          // Remove duplicates by port
          const filtered = prev.filter(item =>
            !(item.type === 'webapp' && item.port === detectedWebApp.port)
          );
          return [webAppPreviewItem, ...filtered];
        });

        setDetectedWebApps(prev => [...prev, detectedWebApp]);
      }
    }
  };

  // Handle matplotlib plot generation
  const handleMatplotlibGenerated = (data: any) => {
    const base64Image = data.base64_image || data.image_data || '';
    const imageSizeKB = Math.round((base64Image.length * 3) / 4 / 1024);

    if (imageSizeKB > 5000) {
      Alert.alert(
        'Image Too Large',
        `Image size (${imageSizeKB}KB) exceeds limit. Please reduce image resolution.`
      );
      return;
    }

    const newItem: PreviewItem = {
      id: Date.now().toString(),
      type: 'matplotlib',
      name: data.title || 'Generated Plot',
      description: data.description || 'Matplotlib plot generated from command execution',
      status: 'ready',
      path: data.filename,
      size: `${imageSizeKB}KB`,
      timestamp: new Date().toLocaleString(),
    };

    setPreviewItems(prev => [newItem, ...prev]);
    setImageData(base64Image);
    setSelectedItem(newItem);
    setShowFullscreen(true);

    // W&B統合: Matplotlibプロットを自動でW&Bにログ
    if (currentExperiment) {
      integrateWithWandB(newItem);
    }
  };

  const getFilteredItems = () => {
    if (activeTab === 'commands') return [];
    if (activeTab === 'all') return previewItems;
    if (activeTab === 'wandb') return []; // W&Bタブでは通常のプレビューアイテムを除外
    return previewItems.filter(item => item.type === activeTab);
  };

  // Get unique categories from commands
  const getCategories = () => {
    const categories = ['all', ...new Set(commands.map(cmd => cmd.category))];
    return categories;
  };

  // Get category display info
  const getCategoryInfo = (category: string) => {
    const categoryMap = {
      all: { name: '全て', icon: '🔧', color: '#4CAF50' },
      basic: { name: '基本', icon: '📚', color: '#2196F3' },
      visualization: { name: '可視化', icon: '📊', color: '#FF9800' },
      nlp: { name: 'NLP', icon: '📝', color: '#9C27B0' },
      multiagent: { name: 'マルチエージェント', icon: '🤖', color: '#FF5722' },
      machine_learning: { name: '機械学習', icon: '📈', color: '#795548' },
      realtime: { name: 'リアルタイム', icon: '⚡', color: '#607D8B' },
      server: { name: 'サーバー', icon: '🌐', color: '#00BCD4' },
      system: { name: 'システム', icon: '⚙️', color: '#8BC34A' },
      interactive: { name: 'インタラクティブ', icon: '🎮', color: '#E91E63' }
    };
    return categoryMap[category] || { name: category, icon: '📦', color: '#666' };
  };

  // Commands section rendering with enhanced filtering
  const renderCommandsSection = () => {
    const categories = getCategories();

    return (
      <ScrollView style={styles.commandsContainer} showsVerticalScrollIndicator={false}>
        <View style={styles.commandsHeader}>
          <Text style={styles.commandsTitle}>🔧 Enhanced Command Execution</Text>
          <Text style={styles.commandsDescription}>
            Execute enhanced commands with Japanese support, ML pipelines, and multi-agent systems
          </Text>

          {/* 動的コマンド生成エリア */}
          <View style={styles.dynamicGenerationArea}>
            <Text style={styles.dynamicGenerationTitle}>🔄 動的コマンド生成</Text>
            <TextInput
              style={styles.inputTextArea}
              placeholder="シンプルなFlaskアプリケーションを作成してください..."
              placeholderTextColor="#999"
              multiline={true}
              numberOfLines={3}
              value={lastInputText}
              onChangeText={(text) => {
                setLastInputText(text);
                // リアルタイム生成は重いので、ボタンプレスで生成
              }}
            />
            <TouchableOpacity
              style={styles.generateButton}
              onPress={() => generateDynamicCommands(lastInputText)}
              disabled={!lastInputText.trim()}
            >
              <Text style={styles.generateButtonText}>⚡ コマンド生成</Text>
            </TouchableOpacity>

            {/* デモ用テストボタン */}
            <TouchableOpacity
              style={[styles.generateButton, { backgroundColor: '#FF6B6B', marginTop: 8 }]}
              onPress={() => {
                console.log('🧪 デモテスト: Flaskコマンド生成テスト開始');
                const testText = 'シンプルなFlaskアプリケーションを作成してください。ホームページに"Hello World"を表示し、/aboutページに会社情報を表示する機能を含めてください。';
                setLastInputText(testText);
                generateDynamicCommands(testText);
              }}
            >
              <Text style={styles.generateButtonText}>🧪 Flaskテスト</Text>
            </TouchableOpacity>

            {/* 動的生成状況の表示 */}
            <Text style={styles.dynamicStatus}>
              {dynamicCommands.length > 0
                ? `✅ ${dynamicCommands.length}個の動的コマンドが生成されました`
                : lastInputText.trim()
                  ? '💡 コマンド生成ボタンを押してください'
                  : '📝 テキストを入力してください'
              }
            </Text>
          </View>

          {/* Category Filter */}
          <View style={styles.categoryFilterContainer}>
            <Text style={styles.categoryFilterTitle}>📂 カテゴリフィルタ</Text>
            <ScrollView horizontal showsHorizontalScrollIndicator={false} style={styles.categoryScroll}>
              {categories.map((category) => {
                const categoryInfo = getCategoryInfo(category);
                const isActive = commandCategory === category;
                return (
                  <TouchableOpacity
                    key={category}
                    style={[
                      styles.categoryButton,
                      isActive && { backgroundColor: categoryInfo.color }
                    ]}
                    onPress={() => setCommandCategory(category)}
                  >
                    <Text style={styles.categoryIcon}>{categoryInfo.icon}</Text>
                    <Text style={[
                      styles.categoryText,
                      isActive && styles.categoryTextActive
                    ]}>
                      {categoryInfo.name}
                    </Text>
                    <View style={[styles.categoryBadge, { backgroundColor: categoryInfo.color }]}>
                      <Text style={styles.categoryBadgeText}>
                        {category === 'all' ? commands.length : commands.filter(cmd => cmd.category === category).length}
                      </Text>
                    </View>
                  </TouchableOpacity>
                );
              })}
            </ScrollView>
          </View>
        </View>

        {/* Commands List */}
        <View style={styles.commandsList}>
          <View style={styles.commandsStats}>
            <Text style={styles.statsText}>
              📊 表示中: {filteredCommands.length} / {commands.length + dynamicCommands.length} コマンド
            </Text>
            <Text style={styles.statsSubtext}>
              カテゴリ: {getCategoryInfo(commandCategory).name}
              {dynamicCommands.length > 0 && ` | 🔄 動的生成: ${dynamicCommands.length}個`}
            </Text>
            {lastInputText && (
              <Text style={styles.dynamicInputText}>
                💬 入力: "{lastInputText.substring(0, 30)}{lastInputText.length > 30 ? '...' : ''}"
              </Text>
            )}
          </View>

          {filteredCommands.length === 0 ? (
            <View style={styles.emptyCommandsContainer}>
              <Text style={styles.emptyCommandsIcon}>📭</Text>
              <Text style={styles.emptyCommandsTitle}>コマンドが見つかりません</Text>
              <Text style={styles.emptyCommandsText}>
                選択されたカテゴリにはコマンドがありません。他のカテゴリを選択してください。
              </Text>
            </View>
          ) : (
            filteredCommands.map((command) => (
              <CommandExecutionButton
                key={command.id}
                config={command}
                onExecute={executeCommand}
                projectId={projectId}
              />
            ))
          )}
        </View>
      </ScrollView>
    );
  };

  // W&Bコンテンツのレンダリング
  const renderWandBContent = () => {
    return (
      <ScrollView style={styles.wandbContainer} showsVerticalScrollIndicator={false}>
        {/* W&B接続状態 */}
        <View style={styles.wandbStatusCard}>
          <View style={styles.wandbStatusHeader}>
            <Text style={styles.wandbStatusTitle}>🔬 W&B Integration Status</Text>
            <View style={[
              styles.statusIndicator,
              { backgroundColor: wandbConnected ? '#4CAF50' : '#F44336' }
            ]}>
              <Text style={styles.wandbConnectionStatusText}>
                {wandbConnected ? 'Connected' : 'Disconnected'}
              </Text>
            </View>
          </View>
        </View>

        {/* 現在の実験 */}
        <View style={styles.currentExperimentCard}>
          <Text style={styles.wandbCardTitle}>📊 Current Experiment</Text>
          {currentExperiment ? (
            <View style={styles.experimentInfo}>
              <Text style={styles.experimentName}>{currentExperiment.name}</Text>
              <Text style={styles.experimentProject}>Project: {currentExperiment.project}</Text>
              <Text style={styles.experimentStatus}>Status: {currentExperiment.status}</Text>
              <Text style={styles.experimentTime}>
                Started: {currentExperiment.createdAt.toLocaleString()}
              </Text>

              <View style={styles.experimentActions}>
                <TouchableOpacity
                  style={[styles.actionButton, styles.finishButton]}
                  onPress={finishWandBExperiment}
                >
                  <Text style={styles.actionButtonText}>✓ Finish Experiment</Text>
                </TouchableOpacity>
              </View>
            </View>
          ) : (
            <View style={styles.noExperiment}>
              <Text style={styles.noExperimentText}>No active experiment</Text>
              <TouchableOpacity
                style={[styles.actionButton, styles.startButton]}
                onPress={startWandBExperiment}
              >
                <Text style={styles.actionButtonText}>▶️ Start New Experiment</Text>
              </TouchableOpacity>
            </View>
          )}
        </View>

        {/* 実験一覧 */}
        <View style={styles.experimentsListCard}>
          <Text style={styles.wandbCardTitle}>📜 Experiment History</Text>
          {wandbExperiments.length > 0 ? (
            wandbExperiments.slice(0, 5).map((experiment) => (
              <View key={experiment.id} style={styles.experimentItem}>
                <View style={styles.experimentHeader}>
                  <Text style={styles.experimentItemName}>{experiment.name}</Text>
                  <View style={[
                    styles.experimentStatusBadge,
                    { backgroundColor: getExperimentStatusColor(experiment.status) }
                  ]}>
                    <Text style={styles.wandbExperimentStatusText}>{experiment.status}</Text>
                  </View>
                </View>
                <Text style={styles.experimentItemProject}>{experiment.project}</Text>
                <Text style={styles.experimentItemTime}>
                  {experiment.updatedAt.toLocaleString()}
                </Text>
                {Object.keys(experiment.metrics).length > 0 && (
                  <View style={styles.metricsPreview}>
                    <Text style={styles.metricsTitle}>Metrics:</Text>
                    {Object.entries(experiment.metrics).slice(0, 3).map(([key, value]) => (
                      <Text key={key} style={styles.metricItem}>
                        {key}: {typeof value === 'number' ? value.toFixed(4) : value}
                      </Text>
                    ))}
                  </View>
                )}
                {experiment.plots.length > 0 && (
                  <Text style={styles.plotsInfo}>
                    📈 {experiment.plots.length} plot(s) logged
                  </Text>
                )}
              </View>
            ))
          ) : (
            <View style={styles.noExperiments}>
              <Text style={styles.noExperimentsText}>No experiments yet</Text>
              <Text style={styles.noExperimentsSubtext}>
                Start an experiment to track your ML workflow with W&B
              </Text>
            </View>
          )}
        </View>

        {/* W&B統合情報 */}
        <View style={styles.integrationInfoCard}>
          <Text style={styles.wandbCardTitle}>ℹ️ Integration Info</Text>
          <Text style={styles.infoText}>
            • Matplotlib plots are automatically logged to W&B when an experiment is active
          </Text>
          <Text style={styles.infoText}>
            • Experiments track model metrics, plots, and artifacts
          </Text>
          <Text style={styles.infoText}>
            • View detailed experiment data in the W&B dashboard
          </Text>
        </View>
      </ScrollView>
    );
  };

  // 実験ステータスの色を取得
  const getExperimentStatusColor = (status: string) => {
    switch (status) {
      case 'running': return '#2196F3';
      case 'completed': return '#4CAF50';
      case 'failed': return '#F44336';
      case 'crashed': return '#FF5722';
      default: return '#666';
    }
  };

  const getStatusColor = (status: string) => {
    switch (status) {
      case 'ready': return '#4CAF50';
      case 'running': return '#2196F3';
      case 'error': return '#F44336';
      default: return '#666';
    }
  };

  const getTypeIcon = (type: string) => {
    switch (type) {
      case 'matplotlib': return '📊';
      case 'webapp': return '🌐';
      case 'notebook': return '📓';
      default: return '📄';
    }
  };

  const renderPreviewItem = ({ item }: { item: PreviewItem }) => (
    <TouchableOpacity style={styles.previewCard} onPress={() => openPreviewItem(item)}>
      <View style={styles.cardHeader}>
        <View style={styles.cardInfo}>
          <Text style={styles.cardIcon}>{getTypeIcon(item.type)}</Text>
          <View style={styles.cardDetails}>
            <Text style={styles.cardTitle}>{item.name}</Text>
            <Text style={styles.cardDescription}>{item.description}</Text>
          </View>
        </View>
        <View style={[styles.statusBadge, { backgroundColor: getStatusColor(item.status) }]}>
          <Text style={styles.statusText}>{item.status}</Text>
        </View>
      </View>

      {item.type === 'matplotlib' && (
        <View style={styles.cardMetadata}>
          <Text style={styles.metadataText}>📁 {item.path}</Text>
          {item.size && <Text style={styles.metadataText}>📏 {item.size} bytes</Text>}
          {item.timestamp && <Text style={styles.metadataText}>🕒 {item.timestamp}</Text>}
        </View>
      )}

      {item.type === 'webapp' && (
        <View style={styles.cardMetadata}>
          <Text style={styles.metadataText}>🌐 localhost:{item.port}</Text>
          {item.process && <Text style={styles.metadataText}>⚙️ {item.process}</Text>}
        </View>
      )}
    </TouchableOpacity>
  );

  const renderFullscreenContent = () => {
    if (imageData) {
      return (
        <ScrollView
          style={styles.fullscreenContent}
          maximumZoomScale={3}
          minimumZoomScale={1}
          showsVerticalScrollIndicator={false}
          showsHorizontalScrollIndicator={false}
        >
          <Image
            source={{ uri: `data:image/png;base64,${imageData}` }}
            style={styles.fullscreenImage}
            resizeMode="contain"
          />
        </ScrollView>
      );
    }

    if (webAppUrl) {
      return (
        <WebView
          source={{ uri: webAppUrl }}
          style={styles.fullscreenWebView}
          onError={() => Alert.alert('Error', 'Failed to load web application')}
          onLoad={() => console.log('WebView loaded')}
        />
      );
    }

    return (
      <View style={styles.centered}>
        <ActivityIndicator size="large" color="#007AFF" />
        <Text style={styles.loadingText}>Loading preview...</Text>
      </View>
    );
  };

  return (
    <SafeAreaView style={styles.container}>
      <View style={styles.header}>
        <TouchableOpacity
          onPress={() => navigation.goBack()}
          style={styles.backButton}
        >
          <Text style={styles.backText}>← Back</Text>
        </TouchableOpacity>
        <View style={styles.headerInfo}>
          <Text style={styles.title}>Preview</Text>
          <Text style={styles.subtitle}>{projectName || projectId}</Text>
        </View>
        <TouchableOpacity
          style={[styles.refreshButton, !isConnected && styles.disabledButton]}
          onPress={refreshPreviews}
          disabled={!isConnected}
        >
          <Text style={styles.refreshText}>Refresh</Text>
        </TouchableOpacity>
      </View>

      <View style={styles.tabBar}>
        {[
          { key: 'commands', label: 'Commands', icon: '⚡' },
          { key: 'all', label: 'All', icon: '📄' },
          { key: 'matplotlib', label: 'Plots', icon: '📊' },
          { key: 'webapp', label: 'Web', icon: '🌐' },
          { key: 'notebook', label: 'Jupyter', icon: '📓' },
          { key: 'wandb', label: 'W&B', icon: '🔬' },
        ].map((tab) => (
          <TouchableOpacity
            key={tab.key}
            style={[styles.tab, activeTab === tab.key && styles.activeTab]}
            onPress={() => setActiveTab(tab.key as any)}
          >
            <Text style={styles.tabIcon}>{tab.icon}</Text>
            <Text style={[styles.tabText, activeTab === tab.key && styles.activeTabText]}>
              {tab.label}
            </Text>
          </TouchableOpacity>
        ))}
      </View>

      <View style={styles.content}>
        {isLoading ? (
          <View style={styles.centered}>
            <ActivityIndicator size="large" color="#007AFF" />
            <Text style={styles.loadingText}>Connecting...</Text>
          </View>
        ) : !isConnected ? (
          <View style={styles.centered}>
            <Text style={styles.errorIcon}>📡</Text>
            <Text style={styles.errorTitle}>Not Connected</Text>
            <Text style={styles.errorDescription}>
              Unable to connect to server
            </Text>
            <TouchableOpacity style={styles.retryButton} onPress={connectToServer}>
              <Text style={styles.retryText}>Retry Connection</Text>
            </TouchableOpacity>
          </View>
        ) : activeTab === 'commands' ? (
          renderCommandsSection()
        ) : activeTab === 'wandb' ? (
          renderWandBContent()
        ) : getFilteredItems().length === 0 ? (
          <View style={styles.centered}>
            <Text style={styles.emptyIcon}>👁️</Text>
            <Text style={styles.emptyTitle}>No Previews Available</Text>
            <Text style={styles.emptyDescription}>
              Run commands that generate matplotlib plots or start web applications to see previews here.
            </Text>
            <TouchableOpacity style={styles.refreshButton} onPress={refreshPreviews}>
              <Text style={styles.refreshText}>Refresh</Text>
            </TouchableOpacity>
          </View>
        ) : (
          <FlatList
            data={getFilteredItems()}
            renderItem={renderPreviewItem}
            keyExtractor={(item) => item.id}
            style={styles.previewList}
            contentContainerStyle={styles.previewListContent}
            refreshControl={
              <RefreshControl
                refreshing={refreshing}
                onRefresh={refreshPreviews}
                colors={['#007AFF']}
              />
            }
            showsVerticalScrollIndicator={false}
          />
        )}
      </View>

      {/* Fullscreen Modal */}
      <Modal
        visible={showFullscreen}
        animationType="fade"
        presentationStyle="fullScreen"
        onRequestClose={closeFullscreen}
      >
        <SafeAreaView style={styles.fullscreenContainer}>
          <View style={styles.fullscreenHeader}>
            <TouchableOpacity style={styles.closeButton} onPress={closeFullscreen}>
              <Text style={styles.closeText}>✕ Close</Text>
            </TouchableOpacity>
            {selectedItem && (
              <Text style={styles.fullscreenTitle}>{selectedItem.name}</Text>
            )}
          </View>
          {renderFullscreenContent()}
        </SafeAreaView>
      </Modal>
    </SafeAreaView>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f5f5f5',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 15,
    backgroundColor: '#fff',
    borderBottomWidth: 1,
    borderBottomColor: '#e0e0e0',
  },
  backButton: {
    paddingVertical: 8,
    paddingHorizontal: 12,
  },
  backText: {
    color: '#007AFF',
    fontSize: 16,
  },
  headerInfo: {
    flex: 1,
    alignItems: 'center',
  },
  title: {
    fontSize: 18,
    fontWeight: '600',
    color: '#333',
  },
  subtitle: {
    fontSize: 14,
    color: '#666',
    marginTop: 2,
  },
  refreshButton: {
    paddingVertical: 8,
    paddingHorizontal: 16,
    backgroundColor: '#007AFF',
    borderRadius: 8,
  },
  refreshText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '600',
  },
  disabledButton: {
    opacity: 0.5,
  },
  tabBar: {
    flexDirection: 'row',
    backgroundColor: '#fff',
    borderBottomWidth: 1,
    borderBottomColor: '#e0e0e0',
  },
  tab: {
    flex: 1,
    paddingVertical: 15,
    alignItems: 'center',
  },
  activeTab: {
    borderBottomWidth: 2,
    borderBottomColor: '#007AFF',
  },
  tabIcon: {
    fontSize: 20,
    marginBottom: 4,
  },
  tabText: {
    fontSize: 12,
    color: '#666',
  },
  activeTabText: {
    color: '#007AFF',
    fontWeight: '600',
  },
  content: {
    flex: 1,
  },
  centered: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  loadingText: {
    fontSize: 16,
    color: '#666',
    marginTop: 10,
  },
  errorIcon: {
    fontSize: 48,
    marginBottom: 15,
  },
  errorTitle: {
    fontSize: 20,
    fontWeight: '600',
    color: '#333',
    marginBottom: 8,
  },
  errorDescription: {
    fontSize: 16,
    color: '#666',
    textAlign: 'center',
    marginBottom: 20,
  },
  retryButton: {
    backgroundColor: '#007AFF',
    borderRadius: 8,
    paddingVertical: 12,
    paddingHorizontal: 24,
  },
  retryText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
  },
  emptyIcon: {
    fontSize: 48,
    marginBottom: 15,
  },
  emptyTitle: {
    fontSize: 20,
    fontWeight: '600',
    color: '#333',
    marginBottom: 8,
  },
  emptyDescription: {
    fontSize: 16,
    color: '#666',
    textAlign: 'center',
    marginBottom: 20,
  },
  previewList: {
    flex: 1,
  },
  previewListContent: {
    padding: 15,
  },
  previewCard: {
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 15,
    marginBottom: 15,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  cardInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  cardIcon: {
    fontSize: 24,
    marginRight: 12,
  },
  cardDetails: {
    flex: 1,
  },
  cardTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#333',
  },
  cardDescription: {
    fontSize: 14,
    color: '#666',
    marginTop: 2,
  },
  statusBadge: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
  },
  statusText: {
    color: '#fff',
    fontSize: 12,
    fontWeight: '600',
  },
  cardMetadata: {
    marginTop: 8,
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: '#f0f0f0',
  },
  metadataText: {
    fontSize: 12,
    color: '#888',
    marginBottom: 2,
  },
  fullscreenContainer: {
    flex: 1,
    backgroundColor: '#000',
  },
  fullscreenHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 15,
    backgroundColor: 'rgba(0,0,0,0.8)',
  },
  closeButton: {
    paddingVertical: 8,
    paddingHorizontal: 12,
  },
  closeText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
  },
  fullscreenTitle: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
    flex: 1,
    textAlign: 'center',
  },
  fullscreenContent: {
    flex: 1,
  },
  fullscreenImage: {
    width: screenWidth,
    height: screenHeight - 100,
  },
  fullscreenWebView: {
    flex: 1,
  },
  // W&B統合用スタイル
  wandbContainer: {
    flex: 1,
    backgroundColor: '#f8f9fa',
  },
  wandbStatusCard: {
    backgroundColor: '#fff',
    marginHorizontal: 15,
    marginTop: 15,
    borderRadius: 12,
    padding: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  wandbStatusHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  wandbStatusTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#333',
  },
  statusIndicator: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
  },
  wandbConnectionStatusText: {
    color: '#fff',
    fontSize: 12,
    fontWeight: '600',
  },
  currentExperimentCard: {
    backgroundColor: '#fff',
    marginHorizontal: 15,
    marginTop: 10,
    borderRadius: 12,
    padding: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  wandbCardTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#333',
    marginBottom: 12,
  },
  experimentInfo: {
    marginTop: 8,
  },
  experimentName: {
    fontSize: 18,
    fontWeight: '700',
    color: '#007AFF',
    marginBottom: 4,
  },
  experimentProject: {
    fontSize: 14,
    color: '#666',
    marginBottom: 2,
  },
  experimentStatus: {
    fontSize: 14,
    color: '#666',
    marginBottom: 2,
  },
  experimentTime: {
    fontSize: 12,
    color: '#888',
    marginBottom: 12,
  },
  experimentActions: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
  },
  actionButton: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 8,
    marginLeft: 8,
  },
  startButton: {
    backgroundColor: '#4CAF50',
  },
  finishButton: {
    backgroundColor: '#FF9800',
  },
  actionButtonText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '600',
  },
  noExperiment: {
    alignItems: 'center',
    paddingVertical: 20,
  },
  noExperimentText: {
    fontSize: 16,
    color: '#666',
    marginBottom: 12,
  },
  experimentsListCard: {
    backgroundColor: '#fff',
    marginHorizontal: 15,
    marginTop: 10,
    borderRadius: 12,
    padding: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  experimentItem: {
    borderBottomWidth: 1,
    borderBottomColor: '#f0f0f0',
    paddingVertical: 12,
    marginBottom: 8,
  },
  experimentHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 4,
  },
  experimentItemName: {
    fontSize: 14,
    fontWeight: '600',
    color: '#333',
    flex: 1,
  },
  experimentStatusBadge: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
  },
  wandbExperimentStatusText: {
    color: '#fff',
    fontSize: 10,
    fontWeight: '600',
  },
  experimentItemProject: {
    fontSize: 12,
    color: '#666',
    marginBottom: 2,
  },
  experimentItemTime: {
    fontSize: 11,
    color: '#888',
    marginBottom: 8,
  },
  metricsPreview: {
    backgroundColor: '#f8f9fa',
    padding: 8,
    borderRadius: 6,
    marginBottom: 4,
  },
  metricsTitle: {
    fontSize: 12,
    fontWeight: '600',
    color: '#333',
    marginBottom: 4,
  },
  metricItem: {
    fontSize: 11,
    color: '#666',
    marginBottom: 1,
  },
  plotsInfo: {
    fontSize: 11,
    color: '#007AFF',
    fontStyle: 'italic',
  },
  noExperiments: {
    alignItems: 'center',
    paddingVertical: 20,
  },
  noExperimentsText: {
    fontSize: 16,
    color: '#666',
    marginBottom: 4,
  },
  noExperimentsSubtext: {
    fontSize: 12,
    color: '#888',
    textAlign: 'center',
    lineHeight: 16,
  },
  integrationInfoCard: {
    backgroundColor: '#fff',
    marginHorizontal: 15,
    marginTop: 10,
    marginBottom: 20,
    borderRadius: 12,
    padding: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  infoText: {
    fontSize: 12,
    color: '#666',
    marginBottom: 4,
    lineHeight: 16,
  },
  // Commands section styles
  commandsContainer: {
    flex: 1,
    backgroundColor: '#f8f9fa',
  },
  commandsHeader: {
    backgroundColor: '#fff',
    marginHorizontal: 15,
    marginTop: 15,
    borderRadius: 12,
    padding: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  commandsTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#333',
    marginBottom: 8,
  },
  commandsDescription: {
    fontSize: 14,
    color: '#666',
    lineHeight: 18,
  },
  commandsList: {
    paddingHorizontal: 15,
    paddingTop: 10,
    paddingBottom: 20,
  },
  // Enhanced category filtering styles
  categoryFilterContainer: {
    marginTop: 15,
    marginBottom: 10,
  },
  categoryFilterTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: '#333',
    marginBottom: 10,
  },
  categoryScroll: {
    paddingVertical: 5,
  },
  categoryButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#f0f0f0',
    borderRadius: 20,
    paddingHorizontal: 12,
    paddingVertical: 8,
    marginRight: 10,
    minWidth: 100,
  },
  categoryIcon: {
    fontSize: 14,
    marginRight: 6,
  },
  categoryText: {
    fontSize: 12,
    color: '#666',
    fontWeight: '500',
    marginRight: 6,
  },
  categoryTextActive: {
    color: '#fff',
    fontWeight: '600',
  },
  categoryBadge: {
    backgroundColor: '#ccc',
    borderRadius: 10,
    paddingHorizontal: 6,
    paddingVertical: 2,
    minWidth: 18,
    alignItems: 'center',
  },
  categoryBadgeText: {
    color: '#fff',
    fontSize: 10,
    fontWeight: 'bold',
  },
  commandsStats: {
    backgroundColor: '#f8f9fa',
    borderRadius: 8,
    padding: 12,
    marginBottom: 15,
    borderLeftWidth: 4,
    borderLeftColor: '#4CAF50',
  },
  statsText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#333',
    marginBottom: 2,
  },
  statsSubtext: {
    fontSize: 12,
    color: '#666',
  },
  emptyCommandsContainer: {
    alignItems: 'center',
    paddingVertical: 40,
    paddingHorizontal: 20,
  },
  emptyCommandsIcon: {
    fontSize: 48,
    marginBottom: 15,
  },
  emptyCommandsTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#333',
    marginBottom: 8,
    textAlign: 'center',
  },
  emptyCommandsText: {
    fontSize: 14,
    color: '#666',
    textAlign: 'center',
    lineHeight: 20,
  },
  // 動的コマンド生成用スタイル
  dynamicGenerationArea: {
    backgroundColor: '#f0f8ff',
    borderRadius: 12,
    padding: 16,
    marginVertical: 15,
    borderLeftWidth: 4,
    borderLeftColor: '#007AFF',
  },
  dynamicGenerationTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#007AFF',
    marginBottom: 10,
  },
  inputTextArea: {
    backgroundColor: '#fff',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#ddd',
    padding: 12,
    fontSize: 14,
    color: '#333',
    minHeight: 80,
    textAlignVertical: 'top',
    marginBottom: 12,
  },
  generateButton: {
    backgroundColor: '#007AFF',
    borderRadius: 8,
    paddingVertical: 12,
    paddingHorizontal: 20,
    alignItems: 'center',
    alignSelf: 'flex-end',
  },
  generateButtonText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '600',
  },
  dynamicStatus: {
    fontSize: 12,
    color: '#666',
    textAlign: 'center',
    marginTop: 10,
    fontStyle: 'italic',
  },
  dynamicInputText: {
    fontSize: 11,
    color: '#007AFF',
    fontStyle: 'italic',
    marginTop: 4,
  },
});

export default EnhancedPreviewScreen;